### ISSUE TITLE
memory leaks and uninitialized vars

### ISSUE THREAD

**Issue by zebastian** [buddhi1980/mandelbulber2#427] opened 2017-11-05 18:14 UTC
when the program is run with valgrind and a small opencl image is rendered the following issues occur:
- memory is leaked in PutDummyToAlign (maybe false positive?)
- uninitialized values in cImage::CalculatePixel(...)

@buddhi1980 for both issues i could not find any obvious mistakes in those functions. Can you take a look?

**Comment by buddhi1980** [comment] 2017-11-05 19:03
Have you run this test with OpenCL or without?

**Comment by rikardfalkeborn** [comment] 2017-11-05 19:38
Isn't this the leak?

```
	if (missingBytes > 0)
	{
		char *dummyData = new char[missingBytes];
		memset(dummyData, 0, missingBytes);
		array->append(dummyData, missingBytes);
		return missingBytes; // dummyData leaks?
	}
```

Perhaps it could be changed to (completely untested but should be possible if I read the documentation correct):

```
	if (missingBytes > 0)
	{
		array->append(missingBytes, 0);
		return missingBytes;
	}
```

**Comment by rikardfalkeborn** [comment] 2017-11-05 19:49
Seems that functions was introduced in QT 5.7, but just freeing dummyData after it has been appended should work?

**Comment by zebastian** [comment] 2017-11-05 20:57
@buddhi1980 yes, i have run the test with opencl.
@rikardfalkeborn yes, thats the location but i think the  problem is in the surrounding context, where the ao vectors are padded into the buffer. This leak does not happen always with PutDummyToAlign but only on the ao vectors (as far as o know).

**Comment by buddhi1980** [comment] 2017-11-05 21:15
If there is 
```char *dummyData = new char[missingBytes]; ```
then should be 
```delete[] dummyData```

Second problem I will analyze tomorrow. It could be caused by invisible modification of image data by GFX driver. The data is not initialized by CPU but by GPU. But this I need to confirm by test.

**Comment by buddhi1980** [comment] 2017-11-06 17:29
First memory leak fixed in commit https://github.com/buddhi1980/mandelbulber2/commit/53c3c1a1e105f2a38c22c5b0a92cbbfe763dd5ed

uninitialized values in cImage::CalculatePixel(...) is a false positive because data is initialized by GPU so it's not possible to trace by valgrind.

**Closed** 2017-12-30 12:40 UTC
Labels: BUG
