### ISSUE TITLE
Some Abox formulas fail to render with OpenCL

### ISSUE THREAD

**Issue by TasMania17** [buddhi1980/mandelbulber2#559] opened 2018-10-09 23:25 UTC
2.15-dev-alpha2 (alpha3) Ubuntu 18.04, OpenCL mode-full

Abox Mod2 gives a colored frame
Abox Mod11 black frame
Abox Mod12 black frame
Abox Mod 13 colored frame

**Comment by mclarekin** [comment] 2018-10-10 04:36
Tas, they are rendering OK for me. Please attach a screenshot, it would be
interesting  to see the issue, and send some settings.

**Comment by TasMania17** [comment] 2018-10-10 05:42
Thanks mclarekin, here is a screenshot scaled down a bit. All settings and material are default with only one fractal in slot 1.
![aboxmod2emptyscreen](https://user-images.githubusercontent.com/32868462/46715352-560d8280-ccab-11e8-8b8f-fd678d13b76f.png)

**Comment by mclarekin** [comment] 2018-10-10 06:20
what is maximum view distance on render tab set at (default 50?)

**Comment by TasMania17** [comment] 2018-10-10 08:40
The render tab settings are default. While checking I noticed if I untick  'disable for aSurf mode' I get a fractal design - but it's the same design for the fractals I listed. Only the colors change. I have 'hybrid' unticked.

![aboxmod2emptyscreen2](https://user-images.githubusercontent.com/32868462/46723651-0be4cb00-ccc4-11e8-97cb-d76e3806e5b3.png)

I compiled from the git archive. Maybe I did something wrong.

**Comment by mclarekin** [comment] 2018-10-10 11:09
Ok, 
a) I can not reproduce the color or black frame issue. Did the default mandelbox preset render ok?

b) Abox11,12,13, mandelboxs all should have same shape with default settings. The formulas have common transforms (which build the default shape) but each formula has some unique options. Hence they should have the same shape in asurf mode. (The color differences are due to different calcs)

c) I can reproduce your abox-mod2, asurf mode, screen-shot. So that part is working fine.

Assuming the mandelbox preset works, then try to change to the other abox formulas and see if they work now,

If you get same problem, then copy and paste settings in case there is something that should not be there (li.e  contaminated settings file)

**Comment by TasMania17** [comment] 2018-10-11 00:41
Hi mclarekin.
Yes the default mandelbox is OK. I renamed 'mandelbulber_215.ini' and MDBB made a new one.
Abox Mod1 is screwed-up which could be causing my issue. Here is what it renders with all default settings.

![aboxmod1](https://user-images.githubusercontent.com/32868462/46773594-d97db100-cd49-11e8-9d4d-3f8dec54fffb.png)

This computer has Nvidia CUDA and only a K600 graphics card. I have been experimenting with neural graphics so it could be just this computer. I'm not worried about it because I can render most other fractals. :)

**Comment by mclarekin** [comment] 2018-10-11 04:44
Default image is not always what you get when you choose a formula.
If you are starting from scratch, then you have the std mandelbulbfratal
with target at origin (0,0,0) and camera distance of 7. The mandelbulb is
small, but if you now change to Mandelbox ( a bigger fractal) then your
camera will be inside the fractal.

**Comment by mclarekin** [comment] 2018-10-11 04:45
Translation    -    "starting from scratch" = starting at the very beginning

**Comment by mclarekin** [comment] 2018-10-11 06:19
I get the same Abox mod1 image as your screenshot, except not as dark.
I think the original problem was being inside the fractal. If you hit "reset view in the navigation panel you generally zoom out such that you can see the whole fractal.

A lot of  fractals are  less than 2 in dimension, but ausrf/abox/mandelbox are bigger. Some fractals are infinite in size.

**Comment by TasMania17** [comment] 2018-10-11 06:45
Your right mclarekin :) Resetting the view on navigation pane brings those fractals back into view. 
After closing MDBB and restarting, I select an Abox fractal and then reset navigation or it's back to no fractal. For me, selecting an Abox fractal does not load the starting coordinates.

**Comment by mclarekin** [comment] 2018-10-15 09:08
i think this can be closed now

**Closed by mclarekin** 2018-10-15 09:08 UTC
