### ISSUE TITLE
crash to desktop

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#750] opened 2019-12-15 00:53 UTC
from Micheal Benson

these setting cause latest nightly to crash to desktop. As do a lot of others.

# Mandelbulber settings file
# version 2.21
# only modified parameters
[main_parameters]
ambient_occlusion 0.3;
ambient_occlusion_enabled true;
antialiasing_enabled true;
camera 0.7 -1.2 -7;
camera_rotation -90 90 90;
camera_top 0 -1 3.749399456654643e-33;
DE_factor 0.7;
delta_DE_function 4;
delta_DE_method 2;
detail_level 4;
flight_last_to_render 0;
fog_color_2 7400 7b00 ff00;
formula_1 122;
formula_2 1055;
formula_3 1082;
formula_start_iteration_1 1;
formula_start_iteration_3 1;
formula_stop_iteration_2 1;
formula_stop_iteration_3 2;
fov 38.58;
hybrid_fractal_enable true;
image_height 1200;
image_proportion 2;
image_width 1600;
keyframe_last_to_render 0;
main_light_alpha 0;
main_light_colour ff00 ff00 ff00;
mat1_coloring_palette_offset 0.252;
mat1_fractal_coloring_aux_color_scale1 0;
mat1_fractal_coloring_orbit_trap_true false;
mat1_is_defined true;
mat1_specular 1;
mat1_specular_color ff00 ff00 7f00;
mat1_specular_metallic 1;
mat1_specular_metallic_width 2;
mat1_specular_plastic_enable false;
mat1_specular_width 1;
N 30;
primitive_plane_1_enabled true;
primitive_plane_1_position 0.3703528357100048 0.01180154760125207 0.3225635998630798;
primitive_plane_1_rotation -90 0 0;
raytraced_reflections true;
spherical_folding true;
spherical_folding_inner 0.25;
spherical_folding_outer 0.5;
target 0.7 -1.2 0;
textured_background_map_type 2;
view_distance_max 34.54479602171055;
volumetric_fog_colour_1_distance 0.05625;
volumetric_fog_colour_2_distance 0.1125;
volumetric_fog_density 2;
volumetric_fog_distance_factor 0.1125;
volumetric_fog_distance_from_surface 0.1;
volumetric_light_DE_Factor 2;
[fractal_1]
analyticDE_tweak_005 0.45;
transf_folding_value 1.97;
transf_offset -0.03;
[fractal_2]
analyticDE_enabled_false true;
analyticDE_offset_0 1;
mandelbox_offset -0.7 1.1 -0.5;
transf_addition_constant 0.7 0.3 0;
[fractal_3]
transf_constant_multiplierC_111 0.9 0.7 -1.1;
transf_function_enabled_false true;
transf_function_enabledAx_false true;
transf_function_enabledAy_false true;
transf_function_enabledAz_false true;
transf_scale 1.68;

**Comment by mclarekin** [comment] 2019-12-15 00:55
I can reproduce in Win10 OS full mode

last part of log

PID: 16656, time: 139.334, Saving settings started, value = C:\Users\graeme\mandelbulber\.autosave.fract
PID: 16656, time: 139.342, Autosave finished
PID: 16656, time: 139.347, cUndo::Store() started
PID: 16656, time: 139.353, cUndo::Store() finished
PID: 16656, time: 139.358, cRenderJob::cRenderJob
PID: 16656, time: 139.363, cRenderJob::Init id = 1
PID: 16656, time: 139.369, cRenderJob::InitImage
PID: 16656, time: 139.375, complexImage allocated
PID: 16656, time: 139.380, cPrimitives::cPrimitives(const cParameterContainer *par) started
PID: 16656, time: 139.387, cPrimitives::cPrimitives(const cParameterContainer *par) finished
PID: 16656, time: 139.393, cFractal::RecalculateFractalParams(void)
PID: 16656, time: 139.399, cFractal::RecalculateFractalParams(void)
PID: 16656, time: 139.406, cFractal::RecalculateFractalParams(void)
PID: 16656, time: 139.411, cFractal::RecalculateFractalParams(void)
PID: 16656, time: 139.417, cFractal::RecalculateFractalParams(void)
PID: 16656, time: 139.423, cFractal::RecalculateFractalParams(void)
PID: 16656, time: 139.429, cFractal::RecalculateFractalParams(void)
PID: 16656, time: 139.434, cFractal::RecalculateFractalParams(void)
PID: 16656, time: 139.440, cFractal::RecalculateFractalParams(void)
PID: 16656, time: 139.445, Init renderData
PID: 16656, time: 139.452, Preparation of lights started
PID: 16656, time: 139.456, cPrimitives::cPrimitives(const cParameterContainer *par) started
PID: 16656, time: 139.464, cPrimitives::cPrimitives(const cParameterContainer *par) finished
PID: 16656, time: 139.470, cFractal::RecalculateFractalParams(void)
PID: 16656, time: 139.476, cFractal::RecalculateFractalParams(void)
PID: 16656, time: 139.481, cFractal::RecalculateFractalParams(void)
PID: 16656, time: 139.486, cFractal::RecalculateFractalParams(void)
PID: 16656, time: 139.493, cFractal::RecalculateFractalParams(void)
PID: 16656, time: 139.499, cFractal::RecalculateFractalParams(void)
PID: 16656, time: 139.504, cFractal::RecalculateFractalParams(void)
PID: 16656, time: 139.510, cFractal::RecalculateFractalParams(void)
PID: 16656, time: 139.515, cFractal::RecalculateFractalParams(void)
PID: 16656, time: 139.520, Preparation of lights finished
PID: 16656, time: 139.525, cPrimitives::cPrimitives(const cParameterContainer *par) started
PID: 16656, time: 139.531, cPrimitives::cPrimitives(const cParameterContainer *par) finished
PID: 16656, time: 139.536, cFractal::RecalculateFractalParams(void)
PID: 16656, time: 139.542, cFractal::RecalculateFractalParams(void)
PID: 16656, time: 139.548, cFractal::RecalculateFractalParams(void)
PID: 16656, time: 139.555, cFractal::RecalculateFractalParams(void)
PID: 16656, time: 139.561, cFractal::RecalculateFractalParams(void)
PID: 16656, time: 139.568, cFractal::RecalculateFractalParams(void)
PID: 16656, time: 139.574, cFractal::RecalculateFractalParams(void)
PID: 16656, time: 139.581, cFractal::RecalculateFractalParams(void)
PID: 16656, time: 139.587, cFractal::RecalculateFractalParams(void)
PID: 16656, time: 139.593, Setting parameters for OpenCL rendering
PID: 16656, time: 139.599, Constant buffer size [KB], value = 56.2813
PID: 16656, time: 139.605, Creating dynamic data for textures
PID: 16656, time: 139.610, OpenCL - BuildAllTexturesData()
PID: 16656, time: 139.616, OpenCL - BuildAllTexturesData() finished
PID: 16656, time: 139.622, Created dynamic data for textures, value = 16
PID: 16656, time: 139.627, Creating dynamic data for OpenCL rendering
PID: 16656, time: 139.634, Created dynamic data for OpenCL rendering, value = 8864
PID: 16656, time: 139.639, Build parameters, value = -w -cl-single-precision-constant -cl-denorms-are-zero -cl-mad-enable -cl-fast-relaxed-math -DOPENCL_KERNEL_CODE -DFULL_ENGINE -DIS_HYBRID -DANALYTIC_JOS_KLEINIAN_DE -DANALYTIC_DE -DFORMULA_ITER_0=JosKleinianIteration -DFORMULA_ITER_1=TransfSphericalInvIteration -DFORMULA_ITER_2=TransfSinOrCosIteration -DSPHERICAL_FOLDING -DPERSP_THREE_POINT -DSHADOWS -DGLOW -DSIMPLE_GLOW -DANTIALIASING -DNUMBER_OF_TEXTURES=0 -DUSE_PLANAR_MAPPING -DMAT_ARRAY_SIZE=2 -DUSE_FRACTAL_COLORING -DREFLECTIONS_MAX=1 -DUSE_SURFACE_GRADIENT -DUSE_PRIMITIVE_PLANE -DUSE_PRIMITIVES -DCODEHASH=20c2ed36b6c116649b109b987de76b5d
PID: 16656, time: 141.453, OpenCl kernel program successfully compiled
PID: 16656, time: 141.458, Program size, value = 313369
PID: 16656, time: 141.463, cOpenClEngineRenderFractal: Opencl DOF build time [s], value = 1.82386
PID: 16656, time: 141.468, Get info for device, value = 0
PID: 16656, time: 141.473, CL_KERNEL_WORK_GROUP_SIZE, value = 384
PID: 16656, time: 141.477, CL_KERNEL_PREFERRED_WORK_GROUP_SIZE_MULTIPLE, value = 32
PID: 16656, time: 141.484, cOpenClEngine::InitOptimalJob(): stepSize, value = 24576
PID: 16656, time: 141.489, cOpenClEngine::InitOptimalJob(): stepSizeX, value = 128
PID: 16656, time: 141.494, cOpenClEngine::InitOptimalJob(): stepSizeY, value = 192
PID: 16656, time: 141.499, OpenCl render fractal - needed mem:, value = 0.5625
PID: 16656, time: 141.504, Allocating OpenCL buffer for constants
PID: 16656, time: 141.509, Allocating OpenCL buffer for dynamic data
PID: 16656, time: 141.513, Allocating OpenCL buffer for texture data
PID: 16656, time: 141.520, Starting RenderMulti()
PID: 16656, time: 141.525, Setting grid size to 12 x 6
PID: 16656, time: 141.530, Writing OpenCL input buffer
PID: 16656, time: 141.536, Writing OpenCL texture buffer
PID: 16656, time: 141.542, Writing OpenCL constant buffer
PID: 16656, time: 141.549, Preparing buffer for background
PID: 16656, time: 141.554, Creating threads for OpenCL workers
PID: 16656, time: 141.560, Thread for OpenCL worker0 create
PID: 16656, time: 141.565, Thread 0 started
PID: 16656, time: 141.565, Assigning kernel parameters
PID: 16656, time: 141.570, Starting main rendering loop
PID: 16656, time: 141.670, Assigning kernel parameters

**Comment by mclarekin** [comment] 2019-12-15 00:59
seems to be anti aliasing, as renders OK with it disabled

**Comment by zebastian** [comment] 2019-12-15 07:25
cannot reproduce on ubuntu. so it is probably a windows specific issue.

**Comment by buddhi1980** [comment] 2019-12-15 15:43
Thanks for reporting it. The error is reproducible with debugger. Will be fixed very soon.

**Comment by buddhi1980** [comment] 2019-12-15 17:06
Fixed.

**Closed by buddhi1980** 2019-12-15 17:06 UTC
Labels: BUG
