### ISSUE TITLE
Add a keyboard layout configuration file

### ISSUE THREAD

**Issue by brunetton** [buddhi1980/mandelbulber2#515] opened 2018-08-08 14:00 UTC
As pointed up in #514 and #502, there's a need to customize keyboards shortcuts.
As a developer; I patch `src/render_window_slots.cpp` file each time I compile Mandelbulber; but I'd love to have a `keyboard.json` file to preciously keep with me :)

I'm sure there's libraries to use to make this easy. 
@buddhi1980 do you plan to implement this ? Or someone else should start a PR ?

Thanks !

**Comment by buddhi1980** [comment] 2018-08-08 15:15
It is duplicate of issue #502
Configuration of keyboard shortcuts is going to be implemented
It is not yet defined when it will happen. Now development team have another priorities (and summer :sun_with_face: )

**Comment by brunetton** [comment] 2018-08-08 22:16
> It is duplicate of issue #502

Not exactly as #502 says that hardcoded shortcuts are not the same in all keyboards layouts; and this tickets is about adding a keyboard layout configuration file.

> It is not yet defined when it will happen. Now development team have another priorities (and summer sun_with_face )

If there's a rainy and boring day during my holidays I'll maybe start something :) (but I'm definitely not a c++ dev)

**Comment by zebastian** [comment] 2018-08-11 08:51
Should be app specific settings in mandelbulber in, configurable in preferences dialog?
I will give more instructions...

**Comment by mancoast** [comment] 2018-08-11 17:12
Is it possible to support gamepad remap in this same file?

**Comment by zebastian** [comment] 2018-08-28 04:42
yes, we can do that

**Comment by mancoast** [comment] 2018-08-28 08:46
Ok awesome! Thoughts on moving gamepad config file to its own issue in the tracker?

**Closed** 2022-02-28 18:54 UTC
Labels: ENHANCEMENT
