### ISSUE TITLE
OpenCL errors in Ubuntu

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#382] opened 2017-10-05 00:50 UTC
Starting /home/graeme/git/mandelbulber2/mandelbulber2/build-mandelbulber-opencl-Desktop-Debug/mandelbulber2...
Mandelbulber 2.12-alpha7
Log file name: /home/graeme/.mandelbulber_log.txt
Detected 8 CPUs
Default data hidden directory: /home/graeme/.mandelbulber/
Default data public directory: /home/graeme/mandelbulber/
Critical: OpenCl ERROR:  "program->build()"  ( -11 )
(../src/opencl_engine.cpp:77, static bool cOpenClEngine::checkErr(cl_int, QString))

OpenCL Build log:
In file included from input.cl:14:
/usr/share/mandelbulber2/opencl/engines/calculate_distance.cl:124:46: error: invalid argument type 'cl_float' (aka 'float') to unary expression

**Comment by mclarekin** [comment] 2017-10-06 05:53
Here is a new message

Default data public directory: /home/graeme/mandelbulber/
radeon: Failed to allocate virtual address for buffer:
radeon:    size      : 65536 bytes
radeon:    alignment : 4096 bytes
radeon:    domains   : 4
radeon:    va        : 0x0000000000800000
radeon: Failed to deallocate virtual address for buffer:
radeon:    size      : 65536 bytes
radeon:    va        : 0x800000
radeon: Failed to allocate virtual address for buffer:
radeon:    size      : 65536 bytes
radeon:    alignment : 4096 bytes
radeon:    domains   : 4
radeon:    va        : 0x0000000000800000
radeon: Failed to deallocate virtual address for buffer:
radeon:    size      : 65536 bytes
radeon:    va        : 0x800000
radeonsi: Failed to create a context.
Critical: OpenCl ERROR:  "program->build()"  ( -11 )
(../src/opencl_engine.cpp:77, static bool cOpenClEngine::checkErr(cl_int, QString))

OpenCL Build log:
In file included from input.cl:15:
/usr/share/mandelbulber2/opencl/engines/calculate_distance.cl:124:46: error: invalid argument type 'cl_float' (aka 'float') to unary expression

**Comment by insidetasmania** [comment] 2017-10-07 23:15
This error only effects the AMD implementation of OpenCL in Ubuntu. I don't think the error is in the Mandelbulber code. The error looks suspiciously like this one picked-up by the blender community:
[https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=857718](url)
The bug is in mesa-opencl-icd LLVM versions before v5. 
Apparently patches are available.

**Comment by mclarekin** [comment] 2017-10-07 23:49
My current guess is related to  is DRI prime. I need to do a backup before trying thre code below, as there may be potential of a black screen

graeme@graeme-Satellite-P50-B:~$ xrandr --listproviders
Providers: number : 2
Provider 0: id: 0x6a cap: 0x9, Source Output, Sink Offload crtcs: 3 outputs: 2 associated providers: 1 name:modesetting
Provider 1: id: 0x45 cap: 0x6, Sink Output, Source Offload crtcs: 6 outputs: 0 associated providers: 1 name:VERDE @ pci:0000:01:00.0

 existing glxinfo
graeme@graeme-Satellite-P50-B:~$ glxinfo | grep "OpenGL renderer"
OpenGL renderer string: Mesa DRI Intel(R) Haswell Mobile

 this should change the order of providers.

**xrandr --setprovideroffloadsink 1 0**

**Comment by insidetasmania** [comment] 2017-10-08 22:26
I wonder if this error is caused by OpenCL version 1.1? That version is from June 2010 and may not be supported by the Mandelbulber2 code.

**Comment by mclarekin** [comment] 2017-10-09 00:27
I did notice the openCL  ver 1.1 in the driver name,

However my gut feeling is that there may be more than one issue that is
causing me problems

The below is dealing with  having two GPUs


https://wiki.archlinux.org/index.php/PRIME


this is using a program called bumbelbee
https://bbs.archlinux.org/viewtopic.php?id=222737

which I haven't checked out yet

**Comment by mclarekin** [comment] 2017-10-09 04:10
I ran    xrandr --setprovideroffloadsink 1 0, safe, no black screen

* OLD  glxinfo*
graeme@graeme-Satellite-P50-B:~$ glxinfo | grep "OpenGL renderer"
OpenGL renderer string: Mesa DRI Intel(R) Haswell Mobile


*NEW glx info   NO CHANGE*
graeme@graeme-Satellite-P50-B:~$ glxinfo | grep "OpenGL renderer"
OpenGL renderer string: Mesa DRI Intel(R) Haswell Mobile


*OLD DRI_PRIME=1 glxinfo *
graeme@graeme-Satellite-P50-B:~$ DRI_PRIME=1 glxinfo | grep "OpenGL
renderer"
radeon: Failed to allocate virtual address for buffer:
radeon:    size      : 65536 bytes
radeon:    alignment : 4096 bytes
radeon:    domains   : 4
radeon:    va        : 0x0000000000800000
....
radeon:    va        : 0x0000000000800000
radeon: Failed to deallocate virtual address for buffer:
radeon:    size      : 65536 bytes
radeon:    va        : 0x800000
radeonsi: Failed to create a context.
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  155 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  44
  Current serial number in output stream:  43

*NEW DRI_PRIME=1 glxinfo   BIG CHANGE*
graeme@graeme-Satellite-P50-B:~$ DRI_PRIME=1 glxinfo | grep "OpenGL
renderer"
OpenGL renderer string: AMD CAPE VERDE (DRM 2.49.0 / 4.10.0-35-generic,
LLVM 6.0.0)





graeme@graeme-Satellite-P50-B:~$ clinfo
Number of platforms                               1
  Platform Name                                   Clover
  Platform Vendor                                 Mesa
  Platform Version                                OpenCL 1.1 Mesa
17.3.0-devel - padoka PPA
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd
  Platform Extensions function suffix             MESA

  Platform Name                                   Clover
Number of devices                                 1
  Device Name                                     AMD CAPE VERDE (DRM
2.49.0 / 4.10.0-35-generic, LLVM 6.0.0)
  Device Vendor                                   AMD
  Device Vendor ID                                0x1002
  Device Version                                  OpenCL 1.1 Mesa
17.3.0-devel - padoka PPA
  Driver Version                                  17.3.0-devel - padoka PPA
  Device OpenCL C Version                         OpenCL C 1.1
  Device Type                                     GPU
  Device Profile                                  FULL_PROFILE
  Max compute units                               10
  Max clock frequency                             625MHz
  Max work item dimensions                        3
  Max work item sizes                             256x256x256
  Max work group size                             256
  Preferred work group size multiple              64
  Preferred / native vector sizes
    char                                                16 / 16
    short                                                8 / 8
    int                                                  4 / 4
    long                                                 2 / 2
    half                                                 8 / 8
(cl_khr_fp16)
    float                                                4 / 4
    double                                               2 / 2
(cl_khr_fp64)
  Half-precision Floating-point support           (cl_khr_fp16)
    Denormals                                     No
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 No
    Round to infinity                             No
    IEEE754-2008 fused multiply-add               No
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Single-precision Floating-point support         (core)
    Denormals                                     No
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 No
    Round to infinity                             No
    IEEE754-2008 fused multiply-add               No
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Double-precision Floating-point support         (cl_khr_fp64)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Address bits                                    64, Little-Endian
  Global memory size                              2147483648
<(214)%20748-3648> (2GiB)
  Error Correction support                        No
  Max memory allocation                           1503238553 (1.4GiB)
  Unified memory for Host and Device              No
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       32768 bits (4096 bytes)
  Global Memory cache type                        None
  Image support                                   No
  Local memory type                               Local
  Local memory size                               32768 (32KiB)
  Max constant buffer size                        1503238553 (1.4GiB)
  Max number of constant args                     16
  Max size of kernel argument                     1024
  Queue properties
    Out-of-order execution                        No
    Profiling                                     Yes
  Profiling timer resolution                      0ns
  Execution capabilities
    Run OpenCL kernels                            Yes
    Run native kernels                            No
  Device Available                                Yes
  Compiler Available                              Yes
  Device Extensions
cl_khr_byte_addressable_store cl_khr_global_int32_base_atomics
cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics
cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics
cl_khr_int64_extended_atomics cl_khr_fp64 cl_khr_fp16

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  Clover
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [MESA]
  clCreateContext(NULL, ...) [default]            Success [MESA]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in
platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  Success (1)
    Platform Name                                 Clover
    Device Name                                   AMD CAPE VERDE (DRM
2.49.0 / 4.10.0-35-generic, LLVM 6.0.0)
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices
found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in
platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (1)
    Platform Name                                 Clover
    Device Name                                   AMD CAPE VERDE (DRM
2.49.0 / 4.10.0-35-generic, LLVM 6.0.0)

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.2.11
  ICD loader Profile                              OpenCL 2.1




*Attempt to run program in OpenCL*

OpenCL Build log:

In file included from input.cl:14:

/usr/share/mandelbulber2/opencl/engines/calculate_distance.cl:124:46:
error: invalid argument type 'cl_float' (aka 'float') to unary expression

does this mean build does not like ' !calc.....


    if (consts->params.common.iterThreshMode && !
calcParam->normalCalculationMode && !maxiter)

**Comment by mclarekin** [comment] 2017-10-09 04:29
@ K & S, do you get this in QT??


calculate_distance.cl.39 unexpected token "point"

calculate_distance.cl.42 expected a declaration

then lots of      extra ","       warnings

**Comment by insidetasmania** [comment] 2017-10-09 08:55
mclarekin, I'm getting the same error as you and I have just one CPU-GPU.  
This is my error:
_________________________________________________________
OpenCL Build log:
In file included from input.cl:4:
/usr/share/mandelbulber2/opencl/engines/calculate_distance.cl:124:46: error: invalid argument type 'cl_float' (aka 'float') to unary expression

Debug: Opencl build time [s] 0.209384
Debug: Build parameters:  -w -cl-single-precision-constant -cl-denorms-are-zero -DOPENCL_KERNEL_CODE -I"/usr/share/mandelbulber2/opencl/"
Error: Error during compilation of OpenCL program
___________________________________________________________
Have you noticed this line in clinfo:
"Max work item sizes    256x256x256"
On my Nvidia graphics system which works with Mbulber OpenCL clinfo has:
"Max work item sizes   1024x1024x64"
It's as if the distance calculation is going out of range, or something similar that stops all renders.

**Comment by buddhi1980** [comment] 2017-10-09 10:39
I have found the problem. Please test if now works properly.

**Comment by mclarekin** [comment] 2017-10-09 10:54
This will be interesting because I have just got openCL working AMD
platform and i7 cpu, and I do not get the error.

I will now pull and have a look.

On Mon, Oct 9, 2017 at 11:39 PM, Krzysztof Marczak <notifications@github.com

**Comment by mclarekin** [comment] 2017-10-09 21:34
I can no longer get this error, but I have other problems now:)

**Comment by insidetasmania** [comment] 2017-10-12 21:41
This issue is fixed for me thanks buddhi1980.

**Comment by zebastian** [comment] 2017-10-18 04:06
was fixed by buddhi in this commit https://github.com/buddhi1980/mandelbulber2/commit/85ef6098695c2f5008c56849dcf67561aa06c130

**Closed by zebastian** 2017-10-18 04:06 UTC
