### ISSUE TITLE
Randomizer crash selecting an empty variation

### ISSUE THREAD

**Issue by GuidoBartoli** [buddhi1980/mandelbulber2#807] opened 2020-09-13 20:39 UTC
##### System information (version)
- mandelbulber2 => 2.22 (AppImage package)
- Operating System / Platform => Linux Mint 20 (64 bit)
- Compiler => Visual Studio 2015

##### Detailed description

Clicking on a "Select" slot inside the Randomizer before generating variations makes the program crash (`segmentation fault`)

##### Steps to reproduce

1. Open **Mandelbulber v2**
1. Load any preset to start over (I used `mandelbulb_power_9.fract`)
1. Click on RENDER button in the Navigation panel
1. Open _Randomizer_ from Menu (`Edit` --> `Randomize all...`)
1. Click on a _Select_ button inside a variation group

**Comment by buddhi1980** [comment] 2020-09-13 21:04
This bug is a duplicate of issue #800, which is already fixed in 2.23

**Closed by buddhi1980** 2020-09-13 21:04 UTC

**Comment by GuidoBartoli** [comment] 2020-09-13 21:31
Sorry, I should have searched for it before posting.
Thanks, waiting for the next release! :+1:
