### ISSUE TITLE
Clients now save alpha but not color channel

### ISSUE THREAD

**Issue by paigan0** [buddhi1980/mandelbulber2#724] opened 2019-10-11 23:47 UTC
Clients in Netrender now save alpha channels but are not saving color channels!

**Comment by buddhi1980** [comment] 2019-10-12 06:52
I was so focused on additional channels and I missed the most important. I will correct it asap.

**Comment by buddhi1980** [comment] 2019-10-12 07:14
It strange, because it works for me. Have you updated program and client and server side? Are you sure that saving of color channel is still enabled in preferences?

**Comment by buddhi1980** [comment] 2019-10-12 13:35
Problem reproducible under Windows

**Comment by buddhi1980** [comment] 2019-10-12 13:41
It produces following errors:
```
PID: 6224, time: 97.866, Critical: Can't open file for write to NetRender cache  "C:\\Users\\buddh\\mandelbulber\\netrender\\C:/Users/buddh/mandelbulber/netrenderframe_0000001.png" (c:\projects\mandelbulber2\mandelbulber2\src\netrender_file_receiver.cpp:55, void __cdecl cNetRenderFileReceiver::ReceiveHeader(int,__int64,class QString)
```

**Comment by buddhi1980** [comment] 2019-10-12 13:49
The problem is on the clint side because it already send wrong folder name:
```NetRender - SendFileHeader(), name DIR[C:/Users/buddh/mandelbulber/netrender]pid5356_frame_0000005.png size 547244```

**Comment by paigan0** [comment] 2019-10-12 20:01
I DL'd (commit d3694c6e1db10fbbde115a8908e32a08ebac2328) and tried it on 1 server and 3 clients: it still saves alpha and not color. All 4 machines have checked color and alpha and save to separate folder. But only server is writing frames to color folder. all write to alpha folder.

**Comment by paigan0** [comment] 2019-10-12 20:06
I then turned all servers and all clients to save color and not alpha, and not in separate folder, and the server is still the only one that saves frames.

**Comment by buddhi1980** [comment] 2019-10-12 20:08
I already know where is the problem. Now I'm looking for correct solution.
It mostly about difference between "\" under Windows and "/" under all another systems used for separator in file paths.

**Comment by buddhi1980** [comment] 2019-10-13 06:54
Problem fixed in commit https://github.com/buddhi1980/mandelbulber2/commit/fa3e3532e385e027ea86098b9cb17e30d8913cb9
@paigan0 , can you test if it works in your network?

TODO: clean up debug output

**Comment by paigan0** [comment] 2019-10-13 17:48
Everything seems to be working (color and alpha channel, anyway). all frames saving to the folder designated by the server, and the client also writing alpha frames to the subfolder within.

**Comment by buddhi1980** [comment] 2019-10-13 18:31
Thanks for feedback. I'm closing this issue.

**Closed by buddhi1980** 2019-10-13 18:31 UTC
Labels: BUG, REPRODUCIBLE, TO BE TESTED
