### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#606] opened 2018-12-23 01:01 UTC
From Jorge
 CPU should stop after render but it keeps a bit rumbling at around 25% on one core.

Was doing a 2k opencl animation with 500 frames and stopped it at around 115 frames, so maybe memory usage are 'normal', but always MBer stays with this cpu usage. even before getting a GTX960 and using only cpu

25 mins after starting Mber again and writing the previous post it jumped again into 30% and I don't even had used it (all default) so it may be another issue

Btw, I'm using the Mandelbulber version hosted at the AUR (archlinux) repositories.  But it happened on previous versions, which were compiled by me

**Comment by mclarekin** [comment] 2018-12-23 04:54
me : How long does CPU use stay high?
I have just had one in Windows while I was using another program,. Mandelbulber CPU suddenly went up to 20%, the duration was less than 1 minute, before dropping back down

jorge: After going up, always. And it stays usually so unless you close it.

**Comment by mclarekin** [comment] 2018-12-23 04:55
accidentally closed :)

**Comment by TasMania17** [comment] 2019-01-01 06:01
Also using Linux but if no other app open then no CPU usage.
MDBB uses one or two CPU cores while rendering in OCL but CPU goes to zero when rendering finished.

**Comment by buddhi1980** [comment] 2019-02-03 13:07
Probably it was caused by rendering of thumbnails for toolbar. I would close this issue, because it is not reproducible at all.

**Closed by buddhi1980** 2019-02-03 13:07 UTC
Labels: BUG
