### ISSUE TITLE
enhance mesh export

### ISSUE THREAD

**Issue by zebastian** [buddhi1980/mandelbulber2#181] opened 2016-12-11 20:29 UTC
things that sould be considered:
- insert openmp pragma to speedup rendering
- there is some issue with high volume (1500x1500x300 on 16GB RAM) resulting in bad alloc

**Comment by zebastian** [comment] 2017-01-01 14:46
also add cli support

**Comment by zebastian** [comment] 2017-01-05 16:45
and also color support, if doable

**Comment by buddhi1980** [comment] 2017-02-10 18:37
I can confirm that the application can crash when resolution is too high.

**Comment by buddhi1980** [comment] 2017-02-12 09:39
I know why it lead to bad allocs. This is just about of needed amount of memory. There is in the code:
```
	size_t *shared_indices = new size_t[numx * numy * numz * 3];
```
Example
Resulution 1500x1500x1500:

it allocates 1500 * 1500 * 1500 * 3 * sizeof(size_t) 
   = 1500 * 1500 * 1500 * 3 * 8 = 8.1e10 bytes = 81GB !!!

**Comment by zebastian** [comment] 2017-02-12 10:28
Thats too much RAM to ask :(
I need to change this alltogether to make it somehow "stream-able" like the voxel slice export, which works on only a slice at a time.

**Comment by buddhi1980** [comment] 2017-02-12 10:52
I have just tried to import to Blender 500x500x500 Mandelbulb object. It utilized 3.5GB of memory :). Saved ply file had size 250MB.

![image](https://cloud.githubusercontent.com/assets/11696990/22861446/62e4b9b6-f119-11e6-8f93-9f33b60785fe.png)

**Comment by zebastian** [comment] 2017-02-12 12:13
the trick is to remove the internal geometry first, this makes up >90% of object size, which should be ignored. after removal all 3d programs can handle even high quality "hulls"

**Comment by zebastian** [comment] 2017-03-07 18:54
memory problem solved here: https://github.com/buddhi1980/mandelbulber2/commit/1b49609a7bc8f82c943c4b3a496373d6d1602719
I will check, if openmp is possible...

**Comment by mancoast** [comment] 2017-03-07 21:33
Is it possible to implement a Clustering Decimation of the mesh to reduce the number of faces?
http://graphics.stanford.edu/courses/cs468-10-fall/LectureSlides/08_Simplification.pdf

**Comment by buddhi1980** [comment] 2017-03-07 21:40
It is possible, but these algorithms are very complex (actually away from my programming abilities). 
There are already very good programs for it like MeshLab, so why should try to implement it.

**Comment by mancoast** [comment] 2017-03-07 21:58
I suggest we implement inter operation with mesh lab, or try to consume the native mesh lab source.

**Comment by mancoast** [comment] 2017-03-07 23:55
https://github.com/cnr-isti-vclab/meshlab/blob/master/src/meshlabplugins/filter_isoparametrization/parametrizator.h


https://github.com/cnr-isti-vclab/meshlab/blob/master/src/meshlabplugins/filter_meshing/meshfilter.cpp
https://github.com/cnr-isti-vclab/meshlab/blob/master/src/meshlabplugins/filter_meshing/meshfilter.h

  case FP_CLUSTERING                       : return tr("Simplification: Clustering Decimation");
REFERENCE https://github.com/cnr-isti-vclab/meshlab/search?utf8=%E2%9C%93&q=Decimation&type=Code

**Comment by mancoast** [comment] 2017-03-08 00:01
https://github.com/cnr-isti-vclab/meshlab/blob/master/LICENSE.txt
GPLv3
LICENCE enables clean merge. I will proceed and enable compilation.
@zebastian or @buddhi1980 can one of you figure out how to connect after we get past compilation?

**Comment by buddhi1980** [comment] 2017-03-08 06:07
Stop! MeshFilter introduces so  many dependencies. First please analyze what is needed fir implementation, then discuss and after that start adding new complex things. Mesh export is not mainstream functionality of Mandelbulber, so I don't want to double size of the code just for mesh optimization (vcg vode has 100k lines), which can be done by external software. For the same reasons I didn't add mp4 or avi compression.

**Comment by cignoni** [comment] 2017-03-08 07:03
Hi, Instead of MeshLab you should look directly at the vcglib, that is the dependency free c++ library on which meshlab is based. 

BTW, not sure it is the simplest path. Preparing/Cleaning a mesh for 3D printing in many cases is not a straightforward process that requires just a sure sequence of filters. 

Probably it could even be simpler/practical to do the converse: having a meshlab filter that imports a mandelbulb formula+parameter that you have finely tuned inside mandelbuber...

**Comment by mancoast** [comment] 2017-03-08 11:59
Greetings,

Thanks for the feedback. I will model our implementation after the Clustered Decimation available in mesh-filter. The system requires vcglib for mesh-filter. This type of simplification engineering enables the core functionality of 3D printing.  I have to reduce the number of faces before I can import Mandelbulb meshes into SolidWorks for "Print 3D"' option.  

Thanks,
Coast

**Comment by mancoast** [comment] 2017-03-08 14:17
P.S. @buddhi, I think we are all clear with license of mesh lab and the simplification feature seems feasible. Inclusion of additional vcglib requires preprocessors and the mandelbulber build system requires full compilation support without optional vcglib. Filtering of mesh might be considered enhancement. If we are out of scope for this github issue, please let me know.  Thanks!

**Comment by buddhi1980** [comment] 2017-03-08 16:56
Meshlab is very good tool for optimizing meshes, because it has so many different filters. It has additionality very good real time preview. 
If we want to implement something similar in Mandelbulber, it's HUGE work. Integration of vcglib and meshal code will be very difficult and we have no manpower to do this.
I will be against implementing this functionality in Mandelbulber, because it's not reasonable to build the tool which already exist for free.

**Comment by mancoast** [comment] 2017-03-08 18:12
Greetings @buddhi1980!

You're the repo owner, so its ultimately your decision how we process new value.
These github conversations are crucial for strategy and I appreciate your feedback.
It is critical to balance the added value of new features with the burden of extra compilation.

@cignoni has informed us that we can essentially rebuild our own mesh-filter with vcglib.
We did not receive permissions to rework the meshlab file headers, so we require rebuild from scratch.
We should remove this 3rdparty folder before next release. *FOR REFERENCE ONLY*

Please confirm your direction regarding support of mesh filter operation.
The decision point has three basic outcomes:
1.) abandon mesh filter functionality
2.) implement a new mesh filter using vcglib for 2.11
3.) implement a new mesh filter using vcglib for undefined future release

This is an excellent opportunity for a new mandelbulber team member l00king to get involved.
Got any buddies in manufacturing engineering?
Perhaps we can look to @sadaszewski or @cignoni for some more assistance?

Thanks,
coast

**Comment by buddhi1980** [comment] 2017-03-08 18:18
My answer is 3. I'm still open for this functionality, but this definitely not for now. There is a lot of another priorities like OpenCl which are much more beneficial for our application.

**Comment by mancoast** [comment] 2017-03-08 19:15
Excellent Choice, Thanks!

**Comment by cignoni** [comment] 2017-03-08 21:50
My 5 cent to the discussion. If you need to simplify the (wonderful) high resolution convoluted mesh generated by mandelbulb there are different algorithms you can choose according to the final purpose of the mesh. Shortly:
- you target rendering; geometric correctness is not a requirement, you just need things that appear correct. 
- you target fabrication; geometric correctness *IS* a requirement; so you have to use a simplification algorithm that can preserve manifoldness.

Clustering usually creates a lot of non-manifold situations.
Edge-collapse based approaches can preserve the original topology.

Both of them are in vcg. probably it is simpler to look at the examples in the vcglib/apps/ folder than to meshlab filters (easier to be understood probably...)

**Comment by cignoni** [comment] 2017-03-08 21:59
For the memory the trick is to allocate two slices at a time; there is no need to allocate the whole volume. Look at the Resampler class (algorithms/resampler.h in the vcglib or the filter uniform mesh resampling in meshlab).

**Comment by mancoast** [comment] 2017-03-08 22:22
@cignoni Your guidance is valuable.  @buddhi1980 @zebastian Do you understand what he means by allocating two slices at a time instead of the whole volume?   Not spun up on the mesh export, however I predict it will be a very attractive feature in the near future and im excited to get some quotes from the local laser shop.

**Comment by zebastian** [comment] 2017-03-10 23:04
volume processing is memory critical, you cannot load all data into memory for a reasonable big model without blowing your RAM, but 3d processing always data to work on in all 3 dimensions. 
The trick is to keep the third dimension really short (2 at best) and move the two slices pointer in the 3rd dimension through the mesh and process with intelligent algorithms. This makes the whole process "streamable". This is also how i reduced the memory footprint of pmnelia's code here: https://github.com/buddhi1980/mandelbulber2/commit/1b49609a7bc8f82c943c4b3a496373d6d1602719

**Comment by zebastian** [comment] 2017-03-10 23:16
@cignoni thanks for your feedback and thanks for meshlab!

**Comment by mancoast** [comment] 2017-03-10 23:51
Slice and Dice like the MRI.
I remember CT and MRI from medimage lab.

**Closed** 2017-03-13 17:12 UTC
Labels: bug, enhancement, Nice to have, Reproducible
