### ISSUE TITLE
Crashes on Ubuntu 1904 AMD Vega 64 when using OpenCL

### ISSUE THREAD

**Issue by ableeker** [buddhi1980/mandelbulber2#681] opened 2019-07-09 21:01 UTC
- mandelbulber2 => 2.18
- Operating System / Platform => Ubuntu 1904

##### Detailed description

When I enable OpenCL on the Asus RoG Strix RX Vega 64, the Device list recognises it as Radeon RX Vega (VEGA10, DRM 3.27.0, 5.0.0-20-generic, LLVM 8.0.1). New installation of Ubuntu 1904, with Oibaf drivers, and mesa-opencl-icd.
However, when I start to render an image, the status shows Compiling OpenCL programs, and then the program closes down without an error. The last line of log file level 3 shows:
Critical: OpenCl ERROR:  "cl::Image2D(...backgroundImage...)"  ( -59 ) (../src/opencl_engine.cpp:80, static bool cOpenClEngine::checkErr(cl_int, QString)
Log file included.

##### Steps to reproduce

Start the Mandelbulber 2.18.
Enable OpenCL.
Render.

[mandelbulber_log.zip](https://github.com/buddhi1980/mandelbulber2/files/3374816/mandelbulber_log.zip)
[clinfo.txt](https://github.com/buddhi1980/mandelbulber2/files/3374831/clinfo.txt)
[mandelbulber_218.ini.txt](https://github.com/buddhi1980/mandelbulber2/files/3374832/mandelbulber_218.ini.txt)

**Comment by buddhi1980** [comment] 2019-07-10 04:28
It cannot run with OpenCL 1.1 which is provided with open source Mesa driver. You need to amdgpu pro driver. There is needed at least OpenCL 1.2

**Comment by mclarekin** [comment] 2019-07-15 02:09
@ableeker does program now work with a OpenCL 1.2 driver?

**Comment by ableeker** [comment] 2019-07-15 16:49
It took a bit of doing, but I was able to install a later version than 1.1 of OpenCL (amdgpu-pro) on Ubuntu 18.04 after all. And it did work then!
But seeing that amdgpu-pro only runs on Ubuntu 18.04, wouldn't mean that mandelbulber only run on 18.04 as well?

**Comment by buddhi1980** [comment] 2019-07-15 17:07
This is great that you managed to run Mandelbulber with OpenCL or your PC.
In general we are not responsible for graphics drivers. If AMD will provide drivers with OpenCL for newer Ubuntu, then Mandelbulber will work.

**Comment by mclarekin** [comment] 2019-07-16 00:56
Thanks for the update. I had to get a new computer because  there was no
drivers that would work in linux for my old AMD card.  Mandelbulber should
work in later Ubuntu versions, the problem is driver software for some AMD
cards. We will close this issue, however previous issue with Windows
crashing is still a mystery :)

Cheers

**Closed** 2019-07-16 00:56 UTC
