### ISSUE TITLE
weird artifacts on AMD cards

### ISSUE THREAD

**Issue by zebastian** [buddhi1980/mandelbulber2#471] opened 2018-05-13 20:16 UTC
Hey buddhi, i think since the adding / refactoring of the opencl materials i am always getting artifacts on my amd card:

![grafik](https://user-images.githubusercontent.com/7888201/39971426-f816327e-56fa-11e8-8813-9abc9f4e5fd3.png)

Only happens in full mode, tried with and without fast relaxed math -> no difference:

settings used were:
```
# Mandelbulber settings file
# version 2.14
# only modified parameters
[main_parameters]
ambient_occlusion 6;
ambient_occlusion_enabled true;
ambient_occlusion_mode 1;
brightness 1,6;
camera 1,344614394034239 -1,649955541384339 1,337101246967557;
camera_distance_to_target 5,999999999999998;
camera_rotation 9,79024095691917 -14,78933746130749 -2,203844054272068;
camera_top -0,08126854688016884 0,2448233760004033 0,9661557523773022;
delta_DE_function 2;
flight_last_to_render 0;
fog_color_1 ff00 ff00 0000;
fog_color_2 ff00 0000 0000;
fog_color_3 5500 0000 0000;
formula_1 8;
formula_material_id 2;
gamma 0,93;
hdr true;
image_height 1080;
image_width 1920;
keyframe_last_to_render 0;
mat1_is_defined true;
mat1_reflectance 0,48;
mat2_coloring_palette_offset 112,2;
mat2_coloring_palette_size 255;
mat2_coloring_random_seed 174720;
mat2_coloring_speed 0,1;
mat2_fractal_coloring_algorithm 2;
mat2_is_defined true;
mat2_reflectance 0,3;
mat2_specular 0,5;
mat2_surface_color_palette 7d5b01 7e5900 815500 854d00 764c01 604e01 484500 75721a d4daa3 a6c4d5 8cb7fd 7babf9 859fa3 969133 967f01 886500 545200 e5f5fe d9e7fe d5e1b9 ead509 ccb600 7a8a6d bed4fe bcbe7d e29101 8a862a 1e52b0 d3deb2 feb431 9ca367 386ecc bdb932 948b01 33619e 7a8453 c68200 3e5c70 273e32 f3bc11 78a53e 726901 f6f05e b2d68b 809e79 a7cfa2 779370 7b501a eeac53 887868 7d4201 fec479 aa9c9b 83595b dca1a3 947676 e8a7aa cf7173 744e50 fdb9bb ab919c 884d86 e184dc 7c627b 8c448a dc7fd8 7b6590 ce9ffb 786786 483757 c1a4dc 74798b 495992 c7d2ff a2a6bd d8e0ff a7b3e2 7f869d c7d3fc a1a5ad 3f6b70 287178 a7b3b5 1c575d a0f5fe 92a89b 69bc6b adfeaf b2feb4 2d6c2d 9bfb9a b9ffba 3e513e cff5d0 ccfbcd 4c4c40 d4d6b1 b5b67d acad6c 69694b eaed9d dee264 979d01 737443 f1f5a0 bec438 d9e022 4b4e01 a8ad25 e7e3df a9a5a1 ebe6de 8f877d 484036 999087 e9e4e0 cdc7c9 aaa1a2 e1d7d6 ebdfdf bcafaf 887879 5e4e4f 4e3e3f 584849 6b5b5c 7c6c6d 867677 8a7a7b 867677 7c6c6d 6b5b5c 584849 4e3e3f 5e4e4f 887879 bdafaf ecdfdf e2d7d6 aca2a1 d0c7c8 e8e4e0 989087 484036 8f887e ece4db a8a49d e6e3de abaa28 4c4f01 dde210 c1c717 f5f97e 737638 979d00 e1e64a eef280 6c6e2b acac71 b5b876 d8d8a3 4e4e31 cdfacf c9f8ca 345637 b9ffbb 94fe98 197b18 b3feb5 adffaf 50cd53 82b487 a1f4fe 075f69 92bbbf 277178 0b4d56 78868c a4b1de 4f5a81 8b94b7 b3c1f5 6b76a0 a1b4f8 2c428f 475484 967bae 301448 534360 9c68cc 5d3483 a961a7 872b85 6b326a ae5aac 6d1569 926285 e09194 632425 985153 d47778 864646 b17e82 5e2627 937171 faa222 492800 804e20 c48127 563200 56704f 7ea679 506e46 90b66a e1db49 484201 5b8821 cf9a00 152920 29485b 8f5e00 676f3e 1b4786 766d01 9d9813 1448a8 7b8346 f59a03 c1cba1 073c9d 6e6b0f c47f00 a5a967 a3c2fe 566649 aa9a01 d3c104 c7d3a9 cddffe d9f0ff 414000 735501 827102 888528 78949a 6fa1f4 7faffb a0bccd cdd499 726e19 423e00 5a4801 714801 804a00 7e5300 7c5800;
mat2_use_normal_map_texture true;
raytraced_reflections true;
reflections_max 2;
target 0,3581644181430911 4,066785946655577 -0,1944937399619144;
volumetric_fog_colour_1_distance 0,002311972067626513;
volumetric_fog_colour_2_distance 0,004623944135253026;
volumetric_fog_density 0,0331131;
volumetric_fog_distance_factor 0,004623944135253026;
volumetric_fog_enabled true;
[fractal_1]
IFS_rotation_enabled true;
mandelbox_scale -1,73;
[fractal_2]
IFS_rotation_enabled true;
[fractal_3]
IFS_rotation_enabled true;
[fractal_4]
IFS_rotation_enabled true;
```

Can you check, if you get the same artifacted output on your nVidia Card, this way we can make sure its an amd thing...

**Comment by mclarekin** [comment] 2018-05-14 02:10
It is an AMD card thing.  Normal or hybrid mode using openCL "Full"
(change to boolean or add a primitive, then artifacts disaapear)

You should be able to  reproduce with build from commit 30 April
https://github.com/buddhi1980/mandelbulber2/commit/f3b0fdddf5e02a3523a257e53441291a67b7002f

**Comment by buddhi1980** [comment] 2018-05-14 04:36
This problem is very difficult for me, because it's not reproducible on Nvidia. 
@zebastian, can you confirm that if you enabled Boolean mode or add at least one primitive, then it works properly? 
I suppose there is some uninitialized variable in the code when they are disabled. But I have looked into the code many times and see nothing suspicious.

**Comment by mclarekin** [comment] 2018-05-14 05:43
there was not much code added in that commit, so it may have acitvated a
problem from the previous commit?

will Sebastian have time to recreate the commit to see which bit of added
code triggered the problem. All my testing is with win64 appveyor.

On Mon, May 14, 2018 at 4:36 PM, Krzysztof Marczak <notifications@github.com

**Comment by mclarekin** [comment] 2018-05-14 05:52
BTW the problem for me does not always occur  with the first render, there
is a random element, but when it starts it stays.

I am pretty sure that i had it a couple of times in medium mode, and since
Kyzysztofs fix, I have not noticed it.

Some of the artifacts are constant in there location, others are random

**Comment by buddhi1980** [comment] 2018-05-14 08:32
One urgent test to do for @zebastian 
Try to change ray_recursion.cl in line 291
There is:
```
shaderInputData.objectId = rayMarchingOut.objectId;
```

change it to
```
#if (defined(BOOLEAN_OPERATORS) || defined(USE_PRIMITIVES))
shaderInputData.objectId = rayMarchingOut.objectId;
#else
shaderInputData.objectId = 0;
#endif
```

The same change do in line 488

Let me know if it eliminates artifacts

**Comment by mclarekin** [comment] 2018-05-14 09:10
I assume line 78 float3 normal;is OK. With the blue coloring denoting
"normal" being a subroutine or some inline maths.

On Mon, May 14, 2018 at 8:32 PM, Krzysztof Marczak <notifications@github.com

**Comment by zebastian** [comment] 2018-05-14 10:31
@buddhi1980 
i can test this this evening
 thanks for the help!

**Comment by zebastian** [comment] 2018-05-14 17:09
@buddhi1980 Yes, that fixes it!

**Comment by zebastian** [comment] 2018-05-14 17:09
Is this a proper fix, or only a workaround?

**Comment by buddhi1980** [comment] 2018-05-14 17:31
It is workaround, but should work in every case. However I would like root cause of this issue.

**Comment by buddhi1980** [comment] 2018-05-14 18:01
I will keep this issue open until there is no permanent solution.

**Comment by buddhi1980** [comment] 2018-05-27 08:54
I'm closing this issue. If it return, I will do more investigation.

**Closed** 2018-05-27 08:53 UTC
Labels: BUG, CRITICAL, TO BE TESTED
