### ISSUE TITLE
default docks positions possible bug

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#202] opened 2017-01-16 09:27 UTC
For me default docks positions produces the attached
![screenshot from 2017-01-16 19-36-58](https://cloud.githubusercontent.com/assets/12769564/21977403/e4471aa6-dc3a-11e6-9040-c61e4fd837d2.jpg)

**Comment by buddhi1980** [comment] 2017-01-16 16:24
I have the same issue so it's very well reproducible. I will try to find fix for this.

**Comment by buddhi1980** [comment] 2017-01-16 16:35
@mclarekin Check if now is better

**Comment by mclarekin** [comment] 2017-01-17 04:28
![screenshot from 2017-01-17 17-23-29](https://cloud.githubusercontent.com/assets/12769564/22007714/eb97d5d0-dcd9-11e6-8ebc-6d392b11b31b.jpg)
i get this, i do not get my normal  default settings that I get when loading the program.

also I have twice tried +Add current windows settings, named them, but do not get the choice of using them??

**Comment by mclarekin** [comment] 2017-01-17 04:29
oops wrong button

**Comment by mclarekin** [comment] 2017-01-17 04:29
now it is open again

**Comment by mclarekin** [comment] 2017-01-19 01:27
On loading program I get my standard opening state dock positions that I
have had for the last few V2 versions.

click on default docks positions I don't get the same as on opening.

stack all docks looks ok

add current windows settings. I can name and save, but have no idea where
they are saved and have no option to open one (I am assuming that is what
it is for??)

animations dock positions. seems OK. But I would like to save my own layout.

save windows state I am assuming svaes current state that will appear on
loading the program.

On Tue, Jan 17, 2017 at 5:35 AM, Krzysztof Marczak <notifications@github.com

**Comment by mclarekin** [comment] 2017-01-19 01:41
"save windows state I am assuming saves current state that will appear on
loading the program."

yes it does.

 So it seems that if i change things,  I can only get back to my opening
default state by closing and reopening the program

**Comment by mclarekin** [comment] 2017-01-19 03:04
It is clearer in my head now:) This is what I was kind of expecting, two
groups:

 -  User Defined dock settings.
 -  Default dock settings.   are like "factory defaults" that come with the
program.

*User Defined Dock settings*
Open user settings   (has load and delete options)
Add to user settings


*Default dock settings*
Default
Animation Default
Stack All Docks

**Comment by mclarekin** [comment] 2017-01-28 22:45
Add current windows settings.  Is this add current windows layout? I  name and save, but where is it saved so I can check they are there??. I  still get nothing from using this :(

Saved windows layouts. Blank nothing there.

**Comment by buddhi1980** [comment] 2017-01-29 11:12
@zebastian , can you check if it works for you?

**Comment by zebastian** [comment] 2017-01-29 12:16
Yes, nice idea with submenu :)

**Comment by mclarekin** [comment] 2017-01-29 12:37
I cant get it to work.  I add current windos settings, enter a name, OK.
And I cannot find it.

Saved windows settings is a black blank list

**Comment by buddhi1980** [comment] 2017-01-29 12:44
It doesn't work with Gnome Desktop! I have just tested it under Ubuntu with Gnome

**Comment by zebastian** [comment] 2017-01-29 14:06
I will try to find some way around this...

**Comment by zebastian** [comment] 2017-01-29 14:40
i can reproduce, the items get added to the dynamic submenu, but they are not visible.
If i set the text directly on the action `action->setText("blabalbbalalb");`
the text is visible, so it is a display problem.
Since the toolbar is displaying just fine, i think this should be solvable...

**Comment by zebastian** [comment] 2017-01-29 15:17
hmm, cannot get it to work, even the code from the toolbar wont show anything on the menu bar icon

**Comment by zebastian** [comment] 2017-01-29 15:18
probably gnome ignores any custom widgets whatsoever, but i could find any information about this on the internet

**Comment by buddhi1980** [comment] 2017-01-29 15:22
It is not typical to put widgets in menu bar. I have also googled it without success. Probably we need another solution. Adding of items can be as it is now. We will use regular QAction objects.
The question is what would be the easiest way to remove items. Popup window with QComboBox for selection (can be called using "Delete saved layouts" option)?

**Comment by zebastian** [comment] 2017-01-29 16:05
thanks for the good idea, thats the solution!
getting an item popup from an combobox was a one liner:
```
	QString itemEscaped = QInputDialog::getItem(this, tr("Remove window settings"),
		tr("Select window setting to remove"), itemsEscaped, 0, false, &ok);
```
Please check if OK. Feel free to change any texts:
https://github.com/buddhi1980/mandelbulber2/commit/2b2d6bad5626f9f644f22117a1e8928daa85aba3

**Comment by buddhi1980** [comment] 2017-01-29 16:32
Thanks. Works very well with KDE. Now I'm going to test it with GNOME. I suppose it should work.

**Comment by buddhi1980** [comment] 2017-01-29 17:22
Works also with GNOME.

@mclarekin , check if it works on your computer.

**Comment by mclarekin** [comment] 2017-01-29 22:27
Ii can now see the window settings I have saved. Solved.

On Mon, Jan 30, 2017 at 6:22 AM, Krzysztof Marczak <notifications@github.com

**Closed** 2017-01-30 04:41 UTC
