### ISSUE TITLE
Missing progressbar in cli mode

### ISSUE THREAD

**Issue by buddhi1980** [buddhi1980/mandelbulber2#89] opened 2016-03-20 16:49 UTC
After this commit https://github.com/buddhi1980/mandelbulber2/commit/3252bfb58612650b0a41291146a5d725ee66db9f there is no progressbar in cli mode.

**Comment by zebastian** [comment] 2016-03-23 18:09
i could not reproduce this yet, if i invoke the cli with:
./mandelbulber2 -n /usr/share/mandelbulber2/examples/hybrid003.fract
the progressbar gets displayed correctly AFAI can see.
can you give me an example with broken output?

**Comment by buddhi1980** [comment] 2016-03-24 17:13
This is what I get:
./mandelbulber2 --nogui settings.fract
![image](https://cloud.githubusercontent.com/assets/11696990/14024935/efcc6e10-f1eb-11e5-82ad-9496811b99af.png)

**Comment by zebastian** [comment] 2016-03-28 06:39
fixed with  69b6003

**Closed by zebastian** 2016-03-28 06:39 UTC
Labels: bug
