### ISSUE TITLE
intermittent problem, unable to edit regular edit fields

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#594] opened 2018-12-05 00:53 UTC
EDIT **I have the problem at the moment , I see that spinboxes are OK. The actual problem is with the other type of parameter boxes, and also file paths for loading images. Closing program and reinstalling fixes the problem**
Cannot edit Ray Step Multiplier (and other NON spinboxes), mouse pointer will not allow you to backspace to edit parameter or delete or over-type the parameter, however x2, /2 and reset all still work.

**Comment by mclarekin** [comment] 2018-12-05 06:20
I am in no-opencl, and auto refresh is off, i can delete the "8" at the beginning of the yaw value and that is as far as i can go. This is typical of the behavior, you can not get into the decimals part of the value

![mouse](https://user-images.githubusercontent.com/12769564/49493828-6a908480-f8c2-11e8-97ba-f5741b6781e3.JPG)

**Comment by mclarekin** [comment] 2018-12-05 08:04
So far have the problem only in:
Navigation panel, but sweet spot is OK
Rendering Engine, but maximum iters and local server port are ok

**Comment by mclarekin** [comment] 2018-12-06 09:33
the problem occurs in lots of tabs

**Comment by buddhi1980** [comment] 2018-12-06 17:04
The problem is about spinboxes ir regular edit fields?
Ray Step Multiplier is not a spinbox, but just an edit field.

czw., 6 gru 2018 o 10:33 mclarekin <notifications@github.com> napisał(a):

**Comment by mclarekin** [comment] 2018-12-06 18:01
When the problem happens, it effects all regular edit fields where you enter a setting or a file path.

**Comment by buddhi1980** [comment] 2018-12-06 18:14
How to reproduce it? When it happens?

**Comment by mclarekin** [comment] 2018-12-06 19:10
I have no idea. Yesterday  was the first time  that i spent some time
trying to find some answers and eliminate possible factors,

all i found out was:
it happens with all regular edit fields,
it can happen in cpu mode
it can happen with auto refresh off
it can happen when not rendering

**Comment by TBeholder** [comment] 2019-02-26 22:06
As in, the cursor insists on jumping to the very first position of any input fields, and snaps back if moved?

**Comment by mclarekin** [comment] 2019-02-27 01:18
TBeholder, yes.  I still haven't investigated. I suspect mouse navigation may cause it. I seldom use mouse navigation and i seldom have the problem.  The next time it happens, could you advise on what you were doing prior to the problem occurring.

**Comment by TBeholder** [comment] 2019-02-27 05:54
Did nothing unusual - load preset, move camera, undo.
Oh, and it's _per dock_. Not even per group of docks, some on the left and some on the right - so the previous time Navigation, Rendering Engine and Material Editor got affected, but Object Editor and Image Adjustments are not. Quit and start again fixed. Then it happens again, but only to Navigation.
In number fields cursor snaps to the first position, in text to the last.

**Comment by buddhi1980** [comment] 2019-02-27 16:53
Does it happen under Windows or Linux? If Windows, which version. If Linux, which distro, version and which window manager (KDE, Gnome...)?
I have never seen this problem on my PC (nor under Windows, nor under LInux), so I need much more information to be able to reproduce it.

**Comment by mclarekin** [comment] 2019-02-28 03:22
For me , the problem may happen on average only once per month
This is my current info (if my memory was correct) 
WIN10
it happens with all regular edit fields
it can happen in cpu and openCl mode
 it can happen with auto refresh off or on
 it can happen when not rendering

**Comment by mclarekin** [comment] 2019-02-28 04:17
@TBeholder  what version of Mandelbulberv2 are you using?
@buddhi1980 , is it possible this could have been related in anyway to #602 ?

I have tested a few things today but cannot make the problem happen

**Comment by TBeholder** [comment] 2019-03-09 16:54
Mandelbulber 2.16 on Linux, with 2 CPU
Also, the problem eventually _does_ go away on its own - just like it appeared, without obvious reasons (and reappears, on different subsets of docks, repeatedly).

**Comment by buddhi1980** [comment] 2019-07-29 18:02
Fixed by adding by adding event filter for menu shortcuts to disable buttonPressTimer

**Closed by buddhi1980** 2019-07-29 18:02 UTC
Labels: BUG
