### ISSUE TITLE
render of main image can start multiple times

### ISSUE THREAD

**Issue by zebastian** [buddhi1980/mandelbulber2#16] opened 2015-06-13 07:14 UTC
the main image is not thread safe.
If you click very reasonable fast on render. You can produce multiple render jobs at a time.
both renders write to displayed image and modify the progress bar.
This effect only occurs on certain settings. Probably due to how busy qt gui is:

Is it possible to (b)lock the image directly after start?
I tried:

```c++
void cInterface::StartRender(void)
{
	WriteLog("cInterface::StartRender(void)");

	stopRequest = true;
	while (mainImage->IsUsed())
	{
	}

	mainImage->BlockImage(); // this should directly block
```
but this resulted in a tilt, if render button is pressed shortly after another.

steps to reproduce:
with a lot of primitive objects the problem is quite bad.
Here a php script to generate a lot of primitive objects:

sudo apt-get install php5-cli # if not already present

```php
#!/usr/bin/env php
<?php

$out = 'Mandelbulber settings file
# version 2.04
# only modified parameters
[main_parameters]' . PHP_EOL;

for($i = 0; $i < 100; $i++)
	$out .= 'primitive_cylinder_' . $i . '_enabled true;' . PHP_EOL;

$out .= '[fractal_1]
[fractal_2]
[fractal_3]
[fractal_4]';

file_put_contents('settings.fract', $out);
echo PHP_EOL . 'Done' . PHP_EOL;
?>
```

**Comment by mclarekin** [comment] 2015-06-13 07:44
Sebastian is too clever,  and oh so fast at tracking down the problem

yes I was re-rendering fast  (re-positioning a primitive)

Certain settings = 27 primitives plus two water effects and one volumetric light



Probably due to how busy qt gui is: Yes I had  v1.21 running in the background GPU rendering a 3200 x 2400 DL 1 in openCL


I’m impressed. Well done.




Sent from Windows Mail





From: Sebastian Jennen
Sent: ‎Saturday‎, ‎13‎ ‎June‎ ‎2015 ‎7‎:‎14‎ ‎p.m.
To: buddhi1980/mandelbulber2





the main image is not thread safe.
If you click very reasonable fast on render. You can produce multiple render jobs at a time.
both renders write to displayed image and modify the progress bar.
This effect only occurs on certain settings. 

Is it possible to (b)lock the image directly after start:

steps to reproduce:
with a lot of primitive objects the problem is quite bad.
Here a php script to generate a lot of primitive objects:

sudo apt-get install php5-cli # if not already present

#!/usr/bin/env php
<?php

$out = 'Mandelbulber settings file

version 2.04

only modified parameters

[main_parameters]' . PHP_EOL;

for($i = 0; $i < 100; $i++)
$out .= 'primitive_cylinder_' . $i . '_enabled true;' . PHP_EOL;

$out .= '[fractal_1]
[fractal_2]
[fractal_3]
[fractal_4]';

file_put_contents('settings.fract', $out);
echo PHP_EOL . 'Done' . PHP_EOL;
?>

**Comment by buddhi1980** [comment] 2015-06-14 15:26
Fixed by adding processing events in while() loop and repeating stopRequest

	stopRequest = true;
	while (mainImage->IsUsed())
	{
		gApplication->processEvents();
		stopRequest = true;
	}
	mainImage->BlockImage();

**Closed by buddhi1980** 2015-06-14 15:26 UTC
Labels: bug
