### ISSUE TITLE
Numeric setting of parameters breaks randomly

### ISSUE THREAD

**Issue by MeyerAdrian** [buddhi1980/mandelbulber2#682] opened 2019-07-10 16:07 UTC
Hi,
when trying to set values numerically with the keyboard (clicking in the field, selecting the curent value, keyboard entering a new value), the beahviour to overwrite the current value breaks at some point when working with mandelbulber.
Mostly after a couple of minutes working, don't know what the actual reason is.

It then gets the behaviour that the keyboard focus always force jumps to the first character and prepends the value that you enter.
Thus when you have a value of 100 and try to enter 200, it makes 200100.
From that point on it is bsically impossible to work with parameters, other than using the x2 /2 and reset buttons.

Would be great if you could have a look at that (-;

Mandelbulber 2.18-1
Windows 10 64Bit

**Comment by mclarekin** [comment] 2019-07-10 23:01
I think this  is related to issue 594 and 628.  We know it happens but can not find steps to reproduce it.  I have not had this problem for several months, 

Does it only happen with regular edit fields (ie spinboxes are OK) ?
What  area of the program were you working in when the problem starts?

**Comment by MeyerAdrian** [comment] 2019-07-11 07:00
Hey,
sorry, oversaw the other issues I guess.

It only happens to fields with numeric values, but thats a lot (-;
Everything like Image Width / Iterations / Camera x / y /z etc.

Once it breaks it breaks for all these parameter fields in the program
Unfortunately I don't know either hoe to reproduce it. But for me it happens every time I use Mdb, after a couple of minutes.
Then restart fixes it again, temporarily.

**Comment by mclarekin** [comment] 2019-07-11 07:21
yep, thats it,  then. restart to fix.
You may be very helpful as you are getting the problem often.

One suggestion is to video capture your movements from restart to up until
it happens

 let's tick somethings off:

OpenCL ?
what GPU and OS.?
send a settings file

what sort of things are you doing with your mouse and keyboard

**Comment by mclarekin** [comment] 2019-07-11 07:46
are you sure about image width and iterations as they are spinboxes. This
problem usually only happens with regular edit fields like camera, target ,
yaw pitch roll. being edit field, whereas the spinboxes have the little
arrows on the right hand side.

**Comment by MeyerAdrian** [comment] 2019-07-11 13:24
Im gone for a couple days.
Sure I'll try to help find out what it is.

I'll try to provide everything you asked when Im back.
Best

**Comment by mclarekin** [comment] 2019-07-12 00:17
No hurry.
 The video and settings is the main thing.  To be able to reproduce the
issue would make us very  happy :) , as it  has been around for a long
time.

Cheers

Graeme

**Comment by MeyerAdrian** [comment] 2019-07-26 12:25
Hi guys,
so I've finally managed to make a screengrab video of the problem.
It happens a couple of times, in different variations.
Hope this helps!

Would be really awesome if the problem could be tracked down. I have to restart MDB a lot unfortunately.

https://vimeo.com/350305331/9122187138

**Comment by mclarekin** [comment] 2019-07-27 10:35
Thank you very much for doing this.   If you could post your settings (PM
at facebooh if you like),  we can try  and reproduce.
After my initial view I can not see anything obvious that you are doing
that is unusual,  you might be a bug magnet :)

This problem  is very difficult to track down  and I have no experience
with this part of the program.
Do you always have "show cursor" unticked?  If  so  please have it ticked
for a while,  so we can eliminate that as being the problem (or part of the
problem)

**Comment by MeyerAdrian** [comment] 2019-07-27 14:34
Sure, happy to help.

When "show cursor" is enabled it 's the same thing unfortunately.
.fract attached in video description...

**Comment by mclarekin** [comment] 2019-07-27 23:59
OK, it was a very slim chance :)

Your problem may be unique as when I had this problem i could still edit
spinbox parameters, but you are having problems with spinboxes.

Thanks for settings, i am trying but can not reproduce.

Do you have access to another computer?   If so, it would be interesting
to know that the problem occurs for you at the same frequency as on your
own computer..

**Comment by mclarekin** [comment] 2019-07-28 00:14
I have noticed two things

your computer refreshes very fast on auto-refresh

400 frames at 60 fps will not let me refresh last frame to render
(normally- right click - reset to default,  will update this number from 0
to the true value)

**Comment by mclarekin** [comment] 2019-07-28 00:31
that was incorrect, i think there has always been a gltich with the last
frame to render updating in some situations

**Comment by mclarekin** [comment] 2019-07-28 00:35
OK,  try another one. Confirm that your problem still happens with auto
refresh disabled

**Comment by MeyerAdrian** [comment] 2019-07-29 07:36
Yes, I think Auto Refrseh doesn't matter.

I found one thing that is reproducable, at least for me.

- In Keyframe Animation Tab "path for images": Click in here and edit the path (only with keyboard, not select folder dialog) (This works for me as the render farm will take that path and create the folder if not existing, though I think it would be a nice little addon if Mandelbulber would create these folders as well when rendering and not throw an error)

- Now save the .fract

- Click in the  "path for images" and try to edit again (delete a couple chars and replace with others)

- Now after the save, this is broken and the cursor always jumps to after the last character, thus making editing impossible

- After restart it works again


It doesnt fully break all numeric parameters but I'm pretty sure its related. In itself its a bug that forces me to restart MDB every couple minutes.

**Comment by mclarekin** [comment] 2019-07-29 08:12
I will give that a try

BTW when I had the problem  it did not matter if auto-refresh was on or
off. But I  noticed that you  are a fast mouse clicker (fast mouse clicking
can still sometimes cause me to have problems with the program.)

  FYI  problem occurs Linux and Win10.  as well as in both CPU and GPU
modes.  I am still hoping to find out if you are unique in respect to it
happening  with spinbox edit fields, but we only have to other users who
report this problem and for them it is infrequent.

**Comment by mclarekin** [comment] 2019-07-29 08:36
Nope. cannot reproduce.  I know very little about most aspects of the
program and computers in general. Generally  most peoples problems are from
not editing the TDR in registry, you unfortunately have a very unusual
issue.

Have you tried reproducing on another computer?

**Comment by MeyerAdrian** [comment] 2019-07-29 09:14
Hey yes,
just tried on another Computer.
Also with OpenCL Completely disabled in Prefs.
Same Problems.


Also
Win 10 64 Bit
Both very fast Machines
28 Cores (56 MT) 128 GB RAM
Geforce GTX 1080 TI

Other Computer
Different Vendor
Same CPU Specs
Geforce GTX 2080 TI

**Comment by mclarekin** [comment] 2019-07-29 09:39
Really weird
so two things in common
- settings file
- you, lol

and maybe the mouse.


what you have in common with Steve and Michael (who only occasionally have
this problem)  is high end equipment  and netrendering

Jorge is different but does remote rendering on a friends computer sometimes

I am completely different  as i only work on a mid range laptop, but I have
not had the problem for quite a few months.

You are unique with the frequency of the problem

 have you got access to a mid range computer to test?

**Comment by mclarekin** [comment] 2019-07-29 09:53
the only uncommon thing about your settings file that is a bit uncommon is
the using of Stop at Maxiimum Iterations (but Menno Jenson uses that with
high end hardware and i do not recall him having the problem)

can I send your settings file to Steve and Michael to test?

**Comment by buddhi1980** [comment] 2019-07-29 10:26
I have just returned from vacation. I will try to look at this problem deeply. Thanks a lot for big input for this strange issue.

**Comment by MeyerAdrian** [comment] 2019-07-29 11:24
Hey,
sounds great! Looking forward.

@mclarekin 
It happens for me completely indepent on .fract file
On the other PC's I just created the dfault Mandelbulb and started testing, and it still happened.
So guess that has nothing to do with it.

**Comment by buddhi1980** [comment] 2019-07-29 15:11
Success! I found way how to reproduce it in 100% of trials.
1. Keep mouse pointer in area where is rendered fractal
2. Press ctrl+s (instead of save settings using Save from pull down menu)
3. Now edit fields are broken

@MeyerAdrian Do you use ctrl+s for saving?

**Comment by MeyerAdrian** [comment] 2019-07-29 15:51
You genius (-;
Yes I do!

**Comment by buddhi1980** [comment] 2019-07-29 16:20
The problem is in class RenderedImage in events:
```
	void keyPressEvent(QKeyEvent *event) override;
	void keyReleaseEvent(QKeyEvent *event) override;
```
When I disable these events, then it doesn't happen.
Now I need to find why and fix it.

**Comment by buddhi1980** [comment] 2019-07-29 18:03
Fixed by adding by adding event filter for menu shortcuts to disable buttonPressTimer

**Closed by buddhi1980** 2019-07-29 18:03 UTC
Labels: REPRODUCIBLE

**Comment by mclarekin** [comment] 2019-07-29 23:07
explains  users suspecting copy and paste,   they must of been using
shortcuts

**Comment by mclarekin** [comment] 2019-07-29 23:43
out of interest,  would this have effected ctrl mouse wheel?

**Comment by buddhi1980** [comment] 2019-07-30 05:05
ctrl+wheel was handled properly and didn't caused this effect

**Comment by mclarekin** [comment] 2019-07-30 05:08
thanks for confirmation
