### ISSUE TITLE
Image saving is broken on latest nightly.

### ISSUE THREAD

**Issue by degriz** [buddhi1980/mandelbulber2#728] opened 2019-10-16 21:25 UTC
![mber](https://user-images.githubusercontent.com/860491/66960322-26cee580-f064-11e9-90fe-e7652ba4fcdb.PNG)
![frame_0000001](https://user-images.githubusercontent.com/860491/66960104-b4f69c00-f063-11e9-9eae-3920afb26f24.jpg)
![frame_0000008](https://user-images.githubusercontent.com/860491/66960288-099a1700-f064-11e9-9322-3129bf54df31.jpg)

**Comment by mclarekin** [comment] 2019-10-17 00:29
elaborate
 an occasional color bug was fixed, is it related to color? or image not saving?

**Comment by buddhi1980** [comment] 2019-10-17 16:40
@degriz , can you write more about this problem? How to reproduce it? Have you used the newest version on server and client side? What you mean by "saving is broken"?

**Comment by degriz** [comment] 2019-10-17 19:39
Sorry will keep this all here. As discussed on FB, Settings. # Mandelbulber settings file
# version 2.20
# only modified parameters
[main_parameters]
ambient_occlusion 0.5;
ambient_occlusion_enabled true;
ambient_occlusion_fast_tune 0.13;
ambient_occlusion_mode 0;
anim_keyframe_dir M:\wavelength\;
animsound_bandwidth_fractal0_transf_constant_multiplier_122_x 1141;
animsound_bandwidth_fractal0_transf_offset_000_x 861;
animsound_bandwidth_fractal0_transf_offset_000_z 818;
animsound_bandwidth_fractal0_transf_scaleA_1 1723;
animsound_bandwidth_main_primitive_water_1_length 538;
animsound_bandwidth_main_primitive_water_1_relative_amplitude 172;
animsound_decayfilter_fractal0_transf_constant_multiplier_122_z true;
animsound_decayfilter_fractal0_transf_offset_000_z true;
animsound_decayfilter_fractal0_transf_scaleA_1 true;
animsound_decayfilter_main_primitive_water_1_relative_amplitude true;
animsound_enable_fractal0_transf_constant_multiplier_122_x true;
animsound_enable_fractal0_transf_constant_multiplier_122_z true;
animsound_enable_fractal0_transf_offset_000_x true;
animsound_enable_fractal0_transf_offset_000_z true;
animsound_enable_main_primitive_water_1_length true;
animsound_enable_main_primitive_water_1_relative_amplitude true;
animsound_midfreq_fractal0_transf_constant_multiplier_122_x 721;
animsound_midfreq_fractal0_transf_offset_000_x 775;
animsound_midfreq_fractal0_transf_offset_000_z 818;
animsound_midfreq_fractal0_transf_scaleA_1 1400;
animsound_midfreq_main_primitive_water_1_length 528;
animsound_midfreq_main_primitive_water_1_relative_amplitude 409;
animsound_pitchmode_fractal0_transf_constant_multiplier_122_z true;
animsound_pitchmode_fractal0_transf_offset_000_x true;
animsound_pitchmode_fractal0_transf_scaleA_1 true;
animsound_pitchmode_main_primitive_water_1_length true;
animsound_smoothfilter_fractal0_transf_constant_multiplier_122_z true;
animsound_smoothfilter_fractal0_transf_scaleA_1 true;
animsound_smoothfilter_main_primitive_water_1_length true;
animsound_soundfile_fractal0_transf_constant_multiplier_122_x M:\Mounika Triste.mp3;
animsound_soundfile_fractal0_transf_constant_multiplier_122_z M:\Mounika Triste.mp3;
animsound_soundfile_fractal0_transf_offset_000_x M:\Mounika Triste.mp3;
animsound_soundfile_fractal0_transf_offset_000_z M:\Mounika Triste.mp3;
animsound_soundfile_fractal0_transf_scaleA_1 M:\Mounika Triste.mp3;
animsound_soundfile_main_primitive_water_1_length M:\Mounika Triste.mp3;
animsound_soundfile_main_primitive_water_1_relative_amplitude M:\Mounika Triste.mp3;
antialiasing_enabled true;
background_3_colors_enable false;
basic_fog_enabled true;
basic_fog_visibility 30;
box_folding true;
camera_distance_to_target 5.8359055519104;
camera_rotation 27.50154512975686 0.4116105599403968 0.2798003237880041;
camera_top 0.007648870496901695 -0.004117001591694133 0.9999622718273002;
DE_factor 0.125;
DE_thresh 0.008796093022208001;
detail_level 0.25;
file_background X:\video textures\clouds%%%%.png;
file_envmap D:\textures\envmap.jpg;
file_lightmap D:\textures\lightmap.jpg;
flight_last_to_render 0;
formula_1 120;
formula_2 1003;
formula_material_id 5;
formula_start_iteration_2 3;
fov 2;
fractal_enable_2 false;
fractal_position 0 0 2;
frames_per_keyframe 960;
gamma 0.6;
glow_enabled false;
hybrid_fractal_enable true;
image_height 1200;
image_width 2133;
keyframe_frames_per_second 60;
keyframe_last_to_render 0;
main_light_alpha -33;
main_light_colour d500 f600 ff00;
main_light_intensity 0.9;
main_light_position_relative false;
mat1_displacement_texture_height 0.0125;
mat1_fresnel_reflectance true;
mat1_is_defined true;
mat1_reflectance 0.25;
mat1_reflectance_gradient 0 ff8a3a 1000 97bd03 2000 ffffdf 3000 ffff30 4000 0f86c2 5000 ffc3a9 6000 ed2790 7000 54e4ff 8000 ffffff 9000 f6ed56;
mat1_specular_plastic_enable false;
mat1_texture_fractalize true;
mat2_displacement_texture_height 0.8;
mat2_file_color_texture X:\jsplacement\4 square city blocks-Color.png;
mat2_file_displacement_texture X:\jsplacement\4 square city blocks height-Seamless.png;
mat2_is_defined true;
mat2_specular_metallic 1;
mat2_specular_metallic_width 0.5;
mat2_specular_plastic_enable false;
mat2_surface_color ee00 e800 de00;
mat2_surface_gradient_enable false;
mat2_texture_scale 4 4 4;
mat2_use_displacement_texture true;
mat3_coloring_speed 2.5088;
mat3_fractal_coloring_algorithm 1;
mat3_iridescence_enabled true;
mat3_iridescence_subsurface_thickness 1.3;
mat3_is_defined true;
mat3_specular 1;
mat3_specular_metallic 0.5;
mat3_specular_metallic_width 0.25;
mat3_specular_plastic_enable false;
mat3_specular_width 1;
mat3_surface_color_gradient 0 f6c8cb 39 f6b6b4 78 ffffec 117 eef5e5 156 ffc5d0 196 f7fff6 234 feede5 274 f8cbd2 313 edc8d9 352 fbf1e8 392 f3b5c2 431 f2fdff 469 faebee 509 effaea 549 fdcbd4 588 fdd9db 627 f8fff8 666 f7fffb 705 f9f9ef 745 fac9de 784 fea1cd 823 f8f4f5 862 e0609d 901 fbfbfb 941 ff5498 980 f066b1 1018 e76ebb 1058 d162a7 1098 db6097 1137 d27fad 1176 ffedff 1215 d44c8a 1254 fdf4f7 1294 a0438a 1333 dfb8cb 1372 c665b2 1411 bc66af 1450 b861b2 1490 b35eb3 1529 dfe7dc 1568 b58ec3 1606 9348a7 1647 b297cc 1685 ac7eaf 1725 c4b8ce 1764 9f82b8 1803 af59b4 1843 957bc4 1882 956bb3 1921 d2c4db 1960 bc95d4 2000 9d6fc7 2039 b38cc5 2078 966aa7 2117 8d65ac 2156 8176b2 2196 897bc6 2235 7563b5 2274 e0ddf2 2313 9b8ec6 2352 e1ddee 2392 9492dd 2431 b5bfda 2470 b2b6d9 2509 b7bbde 2549 b4b8db 2588 6e83b8 2627 3f5f9a 2666 cdcbd9 2705 627ebd 2745 889bd3 2784 c0c6ea 2823 b5cbe3 2861 b1c3e7 2901 c0b8dd 2940 6196c2 2980 dbe0e4 3019 538bc8 3058 b7d2ed 3098 4e89cd 3137 4481c4 3176 437fb3 3215 4b9dd9 3254 8eb9ec 3294 8fb9df 3333 53a6dc 3371 6394d6 3411 4393da 3450 4182d6 3490 68add4 3529 599cb9 3568 279bcc 3607 3496c7 3647 61a8d6 3686 f6eef9 3725 3584e0 3764 10b5d5 3802 069ecf 3843 9ccce2 3882 35b2e0 3921 91ccf6 3960 a5e4f6 4000 eef4ff 4039 d9e9ff 4078 59c7fa 4117 29b0e7 4156 80d0f3 4196 5ccbf9 4235 84dff2 4274 a9ecf2 4313 d0edf3 4352 bdf2f8 4392 fffdf8 4431 e2f9f1 4470 8edcf3 4509 fffffa 4549 b3daeb 4588 cbe8f8 4627 f8fff3 4666 eef8ef 4705 fff6ff 4745 fff6ff 4784 d3e4f4 4823 d9effc 4862 fbf2f5 4901 f3e5e2 4941 92deda 4980 43b8b0 5019 40b9b2 5058 8dd6dc 5098 ededeb 5137 e5eff0 5176 a7ddc5 5215 f5edeb 5254 d6fbdc 5294 4edcac 5333 b2ccc1 5371 e7f1f0 5411 fffcff 5450 fffdf1 5490 77c4a2 5529 fffafd 5568 92ceb4 5607 90d8b2 5647 e2f1da 5686 b8ceb7 5725 f8f3f0 5764 eeffff 5802 fff6ff 5843 ffebff 5881 f8fffc 5921 ffeffb 5960 52b77f 6000 4cb982 6039 1bb04a 6078 4abb7b 6117 cbe1d5 6156 45bd66 6196 fffdfd 6235 b8e4c9 6274 f0f0e4 6312 1e961b 6352 55af65 6391 ebedff 6431 a6ceb3 6470 6cc06b 6509 8bcf96 6549 aedab7 6588 fffdff 6627 86bb4f 6666 f8ffff 6705 67b120 6745 67b30b 6784 f9fffa 6822 cde9d0 6862 c4d960 6901 cdeca9 6941 9cc500 6980 cad97e 7019 9dc300 7058 91b400 7098 d1d502 7137 d3cf00 7176 cddd00 7215 d4d805 7253 ccde00 7294 e3dd0b 7332 cbd401 7372 fef23a 7411 faf100 7450 ffef07 7490 ffef02 7529 fbeb00 7568 feed09 7607 faeb00 7647 ffeefa 7686 ffcb01 7725 fdc200 7764 fbda59 7803 ffd31d 7843 ffcc24 7882 ffd775 7921 fcfcfe 7960 faab00 8000 ffc77e 8039 efa000 8078 fa9b0d 8117 f8da82 8156 ffe8e4 8196 facf8b 8235 ffe2f2 8274 ff5c00 8313 ea963e 8352 f48927 8392 f2dcce 8431 f37c14 8470 fbffff 8509 f9fafe 8549 fffcf9 8588 fefffd 8627 ebb38e 8666 fa5617 8705 eefdf8 8745 e00a00 8784 ebffec 8823 e62208 8862 e1ffff 8901 eefff5 8941 f7ffff 8980 f5fff0 9019 fffafc 9058 f6ffe7 9098 ff8c7a 9137 f5ffff 9176 ff2c29 9215 f4fff1 9254 f3fff6 9294 f9ffef 9333 ffb59c 9372 f55c57 9411 faffea 9450 fdcec6 9490 de3923 9529 ffedff 9568 fdc2c8 9607 e54350 9647 f8fff3 9686 fff7ff 9725 fffef6 9764 f9c1b0 9803 ffedf2 9843 fffdff 9882 fcf8dd 9921 f4b4b5 9960 f6b6b7;
mat4_is_defined true;
mat4_name metal;
mat4_reflectance 0.87;
mat4_specular 10;
mat4_specular_color 5a00 8100 ff00;
mat4_specular_metallic 0.25;
mat4_specular_metallic_roughness 0.2;
mat4_specular_metallic_width 0.125;
mat4_specular_plastic_enable false;
mat4_specular_width 0.199;
mat4_surface_color 6100 6100 6100;
mat4_use_colors_from_palette false;
mat5_is_defined true;
primitive_water_1_anim_progression_speed 0.5;
primitive_water_1_anim_speed 0.5;
primitive_water_1_enabled true;
primitive_water_1_iterations 3;
primitive_water_1_length 0.8;
primitive_water_1_material_id 2;
primitive_water_1_relative_amplitude 0.4;
primitive_water_1_wave_from_objects_enable true;
primitive_water_1_wave_from_objects_relative_amplitude 0.25;
reflections_max 2;
saturation 1.1;
shadows_cone_angle 4;
SSAO_random_mode true;
target 0.3052086469244188 -0.8236948016527919 2.041924548553139;
textured_background true;
textured_background_map_type 2;
volumetric_fog_colour_1_distance 0.2096313728906;
volumetric_fog_colour_2_distance 0.4192627457812001;
volumetric_fog_density 0.4;
volumetric_fog_distance_factor 0.8385254915624002;
volumetric_fog_enabled true;
[fractal_1]
analyticDE_scale_1 2;
transf_constant_multiplier_122 1 2 4;
transf_function_enabledBx_false true;
transf_function_enabledx_false true;
[fractal_2]
transf_scale 2;
[keyframes]
frame;main_camera_x;main_camera_y;main_camera_z;main_target_x;main_target_y;main_target_z;main_camera_top_x;main_camera_top_y;main_camera_top_z;main_primitive_water_1_length;main_primitive_water_1_relative_amplitude;fractal0_transf_constant_multiplier_122_x;fractal0_transf_constant_multiplier_122_y;fractal0_transf_constant_multiplier_122_z;fractal0_transf_offset_000_x;fractal0_transf_offset_000_y;fractal0_transf_offset_000_z;fractal0_analyticDE_scale_1;fractal0_power;fractal0_transf_scaleA_1;fractal0_transf_scaleB_1;fractal0_alpha_angle_offset;main_fractal_rotation_x;main_fractal_rotation_y;main_fractal_rotation_z;main_fov
0;3;-6;2;0.3052086469244188;-0.8236948016527919;2.041924548553139;0.007648870496901695;-0.004117001591694133;0.9999622718273002;0.8;0.4;1;2;4;0;0;0;2;9;1;1;0;0;0;0;2
1;3;-6;2;0.3958272802558631;-0.942492731584184;1.895730400550883;-0.005262958596637978;0.01790324466674627;0.9998258723883938;0.8;0.4;3;2;8;0;0;0;1;9;1;2;0;0;0;0;2.2
2;3;-6;2;0.4048772066942425;-0.9346543455407881;2.027537738584016;0.004814093706918669;-0.002970011277348822;0.999984001639423;0.8;0.4;5;2;2;0;0;0;1;7;1;1;0;0;0;0;.5
3;3;-6;2;1.389703774197397;-2.789861616072205;2.002541215727168;0.0006642548770002682;-0.0004584125673479308;0.9999996743116352;0.8;0.4;3;2;4;0;0;0;1;8;1;1;0;0;0;0;1.5
4;3;-6;2;0.3386413493046643;-0.818192453514837;1.89940489496542;-0.006264896869051879;0.01619257441427594;0.9998492644399246;0.8;0.4;1;2;8;0;0;0;1;9;1;1;0;0;0;0;0.4
interpolation;morphAkima;morphAkima;morphAkima;morphAkima;morphAkima;morphAkima;morphAkima;morphAkima;morphAkima;morphAkima;morphAkima;morphAkimaAngle;morphAkimaAngle;morphAkima

**Comment by degriz** [comment] 2019-10-17 19:40
Have flushed the opencl cache as per your instructions. Also removed and replaced the drivers with a driver cleaner. Still renders differently on each machine \o/

**Comment by degriz** [comment] 2019-10-17 19:43
> 
> 
> elaborate
> an occasional color bug was fixed, is it related to color? or image not saving?

I thought it was rendering one thing and saving something broken. Turns out the render rig produces a different picture to my main one..Same version of everything, Settings above.

**Comment by degriz** [comment] 2019-10-17 19:51
I have progress of a sort. Both machines now render the same wrong image! 👯 So the next question is: Where did my background animation go? :)

**Comment by buddhi1980** [comment] 2019-10-17 20:05
Is it possible that the problem is related to animated texture backgroung? What if you disable this texture? Do you have correct images on both sides?
Answer for this question will help me a lot.

**Comment by mclarekin** [comment] 2019-10-18 04:40
possibility, were you using medium mode instead of full mode?

**Comment by degriz** [comment] 2019-10-18 09:20
All images come from NAS. Set to the same drive letter on all machines so I can move projects around with no issues.

**Comment by degriz** [comment] 2019-10-18 14:39
I now find that the Server now crashes to desktop after a few minutes. Very simple Abox in Blue. No music/ Nothing fancy at all.

**Comment by degriz** [comment] 2019-10-18 14:41
# Mandelbulber settings file
# version 2.20
# only modified parameters
[main_parameters]
abs_max_marching_step 2;
abs_min_marching_step 2e-15;
advanced_quality true;
ambient_occlusion 0.75;
ambient_occlusion_enabled true;
ambient_occlusion_mode 0;
anim_keyframe_dir M:\retrun of abox2\;
background_3_colors_enable false;
background_color_1 0000 0900 0f00;
background_h_scale 4;
background_v_scale 4;
camera 1.943888087352911 -2.004795462703761 -0.1597324846228173;
camera_distance_to_target 0.006166713777929568;
camera_rotation -42.22334095695776 79.06668646388975 -56.31817384046797;
camera_top -0.9821436518108145 0.1559804726099517 0.1051852621430109;
check_for_bailout_1 false;
constant_DE_threshold true;
contrast 1.2;
DE_factor 0.1;
DE_thresh 7.33264041973751e-06;
DOF_blur_opacity 0.5;
DOF_enabled true;
DOF_focus 0.007638436742126942;
DOF_max_radius 7.82;
DOF_min_samples 20;
DOF_radius 1.25;
DOF_samples 12;
fake_lights_color cd00 ff00 2600;
fake_lights_intensity 0.0625;
fake_lights_max_iter 8;
fake_lights_min_iter 5;
fake_lights_orbit_trap 0.03125 0.015625 0;
fake_lights_orbit_trap_shape sphere;
fake_lights_orbit_trap_size 4;
fake_lights_visibility 2;
fake_lights_visibility_size 1.25;
file_background X:\BACKGROUNDS\blurry-lights.jpg;
file_lightmap G:\Textures\Lightmaps\1.jpg;
flight_last_to_render 0;
fog_color_1 0d00 1200 2b00;
fog_color_2 0f00 1600 1f00;
fog_color_3 0800 3300 3a00;
formula_1 119;
formula_material_id 2;
fov 0.2;
fractal_constant_factor 1 0.9 0.92;
frames_per_keyframe 240;
gamma 0.7;
glow_color_1 4f00 5300 8600;
glow_intensity 0.25;
image_height 720;
image_proportion 4;
image_width 1280;
keyframe_frames_per_second 60;
keyframe_last_to_render 0;
linear_DE_offset 0.2;
main_light_beta 13.45;
main_light_colour 2a00 e300 ff00;
main_light_intensity 1.2;
main_light_position_relative false;
mat1_coloring_palette_offset 0.821;
mat1_coloring_speed 0.5;
mat1_diffuse_gradient 0 b8b8b8 1967 f4f4f4 2836 909090 2922 ffffff 3985 d2d2d2 4712 5e5e5e 4731 e7e7e7 5382 707070 5790 ffffff 5991 7a7a7a 6429 ffffff 6664 d9d9d9 6991 a2a2a2 7343 989898 7426 d4d4d4 7543 e2e2e2 7780 5e5e5e 8388 848484 8858 a9a9a9 9576 606060;
mat1_diffuse_gradient_enable true;
mat1_fractal_coloring_algorithm 1;
mat1_iridescence_intensity 3;
mat1_iridescence_subsurface_thickness 2;
mat1_is_defined true;
mat1_luminosity_gradient 0 2dffdf 197 ff5296 259 00ff30 2432 682e32 2573 15ff10 2617 bd0088 2675 005d78 4660 fcf448 5061 ff00c6 5796 b4ff00 6181 533a2c 6485 b76325 6755 11c200 7361 ff1c65;
mat1_luminosity_gradient_enable true;
mat1_reflectance 0.1;
mat1_reflectance_gradient 0 9a9a9a 1967 434343 2836 787878 2922 ffffff 3985 afafaf 4712 4f4f4f 4731 c1c1c1 5382 5e5e5e 5790 ececec 5991 666666 6429 fdfdfd 6664 b5b5b5 6991 878787 7343 7f7f7f 7426 b1b1b1 7543 bdbdbd 7780 4f4f4f 8388 6e6e6e 8858 8d8d8d 9576 505050;
mat1_reflectance_gradient_enable true;
mat1_specular 0.8;
mat1_specular_color 1100 aa00 c100;
mat1_specular_metallic 1;
mat1_specular_metallic_roughness 0.2;
mat1_specular_metallic_width 0.5;
mat1_specular_plastic_enable false;
mat1_specular_width 0.7;
mat1_surface_color 4300 a500 c300;
mat1_surface_color_gradient 0 b87f53 402 0631a3 671 03ad6f 1189 d3ac94 1212 6a5cf9 2168 db214c 2658 b0d6d5 4674 dbcea4 4713 53661c 5226 6a71b7 5396 cb4198 6017 4b85df 7288 36b5a1 7432 1bfe10 8223 a582a6 8484 84ed14 8944 8ffe71 9191 977761;
mat1_texture_fractalize true;
mat1_transparency_gradient 0 644568 380 3994b5 1274 e71a79 1682 2c046a 2547 8aebc7 3007 c1caeb 3741 c5dcfd 4357 e6312e 5547 01cf28 5854 523982 5999 6f5101 6039 8c7925 7275 59dad2 7905 302a83 8855 1e7f04 8895 d93033 9540 3ef135;
mat2_coloring_palette_offset 0.821;
mat2_iridescence_enabled true;
mat2_iridescence_intensity 1.5;
mat2_iridescence_subsurface_thickness 2;
mat2_is_defined true;
mat2_name abox blue;
mat2_specular 0.8;
mat2_specular_color 1100 aa00 c100;
mat2_specular_metallic 0.5;
mat2_specular_metallic_width 0.5;
mat2_specular_plastic_enable false;
mat2_specular_width 0.7;
mat2_surface_color 4300 a500 c300;
mat2_use_colors_from_palette false;
perspective_type fish_eye;
reflections_max 1;
saturation 1.5;
target 1.944674096826587 -2.003929324364254 -0.1536777053284884;
textured_background true;
textured_background_map_type 2;
view_distance_max 10.10691949714248;
volumetric_fog_colour_1_distance 4.641437093801332e-05;
volumetric_fog_colour_2_distance 9.282874187602663e-05;
volumetric_fog_distance_factor 0.002970519740032852;
volumetric_fog_enabled true;
[fractal_1]
mandelbox_color 0 0 0;
mandelbox_color_Sp1 0;
mandelbox_scale -1.2;
transf_addition_constant_111 1 1 0.113;
transf_minR2_p25 0.09;
transf_rotation 9 -5 4;
transf_rotation_enabled true;
transf_scale3D_000 0.4 -0.1 0;
transf_start_iterations_C 250;
transf_stop_iterations_C1 12;
transf_stop_iterations_D1 4;
[keyframes]
frame;main_camera_x;main_camera_y;main_camera_z;main_target_x;main_target_y;main_target_z;main_camera_top_x;main_camera_top_y;main_camera_top_z;main_DOF_focus;main_mat1_coloring_palette_offset;main_DOF_radius;main_DOF_max_radius;main_fov
0;1.934783869911413;-2.005410528927077;-0.1762461860598253;1.935909783024639;-2.007090532880146;-0.1756734431623489;-0.4892802338874516;-0.03076997852568968;0.8715836512627859;0.001078364672139287;0.821;5;62.5;0.4
1;1.934499522791973;-2.004986247267064;-0.1763908311404843;1.935625435905199;-2.006666251220133;-0.1758180882430079;-0.188656966943738;0.2012548808840109;0.961199782430246;0.0005422850954346359;0.821;1.25;7.82;0.4
2;1.934499522791973;-2.004986247267064;-0.1763908311404843;1.935667046223764;-2.003243662833217;-0.176526538821209;0.1356257063047448;-0.01371831242977426;0.9906651683053252;0.0005422850954346359;0.821;1.25;7.82;0.4
3;1.933805418936719;-2.004872343806332;-0.1762840672070862;1.934789142751569;-1.999712437252807;-0.1757747992258815;0.1307357999721003;-0.1220304445081525;0.9838784077409147;0.0005422850954346359;0.821;1.25;7.82;0.4
4;1.93355121284673;-2.004506656878434;-0.1783047296567279;1.933957661332814;-1.998419202076412;-0.179871114596405;0.1630043606829508;0.2356415419659548;0.9580723574439717;0.004369495902210474;0.821;1.25;7.82;0.4
5;1.93355121284673;-2.004506656878434;-0.1783047296567279;1.932923316564148;-2.002358779750319;-0.1841927036901784;0.1442127112486252;0.9344765407946782;0.3255092757798652;0.004369495902210474;0.821;1.25;7.82;0.4
6;1.933899412382341;-2.004304791253358;-0.1786508477919443;1.941594051058086;-1.999843892006981;-0.1862994909325165;-0.01206056620714929;0.8689886538833195;0.4946850130788472;0.004369495902210474;0.821;1.25;7.82;0.4
7;1.936322156036463;-2.00298018209583;-0.1810032445365866;1.944304111507134;-1.998616133388714;-0.1887534355372452;-0.5293682853961301;0.845576377976795;-0.06906379242704289;0.007638436742126942;0.821;1.25;7.82;0.2
8;1.936322156036463;-2.00298018209583;-0.1810032445365866;1.939159275283814;-1.998288438369789;-0.1825675117527957;-0.8438386304552815;0.5324561764373512;0.06653409595892254;0.007638436742126942;0.821;1.25;7.82;0.2
9;1.943888087352911;-2.004795462703761;-0.1597324846228173;1.948129573857817;-2.005859284770352;-0.1456914482494925;-0.9412324306261279;0.1616371766982737;0.296571972119151;0.007638436742126942;0.821;1.25;7.82;0.2
10;1.943888087352911;-2.004795462703761;-0.1597324846228173;1.944674096826587;-2.003929324364254;-0.1536777053284884;-0.9821436518108145;0.1559804726099517;0.1051852621430109;0.007638436742126942;0.821;1.25;7.82;0.2
interpolation;morphAkima;morphAkima;morphAkima;morphLinear;morphLinear;morphLinear;morphLinear;morphAkima

**Comment by degriz** [comment] 2019-10-19 10:07
This morning have removed ALL Nvidia drivers from both machines and replaced with Creators Edition drivers. All stable for last hour or so.

**Comment by buddhi1980** [comment] 2019-10-19 13:16
90% of crashes are caused by NVidia or AND drivers, but for 100% Mandelbulber is blamed. This is real life of software developer ;P
I happy that you fond the problem. By the today I fixed bug which caused crashes of NetRender client.

**Comment by DeepThread** [comment] 2019-10-22 00:02
Hey Budhhi, do you happen to have a suggestion on which driver to use on the most current nightlies? I have been having some issues with the program closing during render using command line or full gui. I have uninstalled the most recent driver and reverted back to something aside from 436.15 ( I forgot exact version and am away from PC). Im going to try degriz's method later but the creator driver only works on my 1080ti and not my 970 so thats not really the best fix for me. Thank you!

**Comment by buddhi1980** [comment] 2019-10-23 16:02
In general Mandelbulber should work with any version of GFX drivers. The only requirement is to use driver which has OpenCL 1.2. But reality is different. GFX drivers has always a lot of bugs, and because rendering engine in Mandelbulber is very complex, drivers sometimes behaves very weird. Problems caused by drives which we already saw in the past:
- reporting missing opencl.dll
- crashing during compilation of OpenCL programs
- GPU memory leaks (after rendering many frames of animation with DOF there was not enough GPU memory)
- OpenCL compiler errors with correct OpenCL code (MacOS + AMD)
- Slow performance
- Crashing when executing OpenCL kernels (especially Intel OpenCL)
- Missing OpenCL platforms in the system

So my recommendation is to use the newest version of drives and when it doens't work to downgrade drivers to last working version.

BUT! There is one IMPORTANT thing! When you use actual development version of Mandelbulber, and we made changes in data structures (ne features to OpenCL code are constantly added) you need to clear NVidia OpenCL compiler cache. Otherwise rendering will not work or produce unexpected results.  To clear cache you can run rendering one with ticked "Disable OpenCL cache" in preferences dialog or delete ".nv" folder from home directory.

**Closed** 2019-11-10 13:24 UTC
