### ISSUE TITLE
mandelbulber2 cannot be opened because of a problem.

### ISSUE THREAD

**Issue by Amoberk** [buddhi1980/mandelbulber2#848] opened 2021-06-24 15:35 UTC
Hello, I tried to install mandelbulber, bu I get the error in the title, I tried installing the version before the final, only to get the same error and I couldn't find any information on what should I do, so I'm writing here. 

- mandelbulber2 => 2.25
- Operating System / Platform => MacOS BigSur 11.4 running on an m1 MacBook

**Comment by Amoberk** [comment] 2021-06-24 15:45
I have been able to run the program with version 2.23

**Comment by networkpanic** [comment] 2021-07-15 19:02
dupe of #837

**Comment by networkpanic** [comment] 2021-07-15 19:02
we are working on getting the macos world shiny again
can't give an ETA yet

**Closed by networkpanic** 2021-07-15 19:02 UTC
Labels: mac
