### ISSUE TITLE
Missing Widgets On Mandelbulber 2.17

### ISSUE THREAD

**Issue by TasMania17** [buddhi1980/mandelbulber2#624] opened 2019-02-28 00:30 UTC
- mandelbulber2 => 2.17
- Operating System / Platform => Ubuntu 18.04
- Compiler => Qt Creator

Updating Mandelbulber from 2.17-beta to 2.17. Program works OK but 3 widgets are missing on main screen "Load' 'Save' 'Reset'

Error message in terminal:
Warning: QObject::connect: No such slot cButtonResetSettingsFromWidget::slotPressedButtonLocalLoad() in ../qt/buton_reset_settings_from_widget.cpp:47
((null):0, (null))

Warning: QObject::connect: No such slot cButtonResetSettingsFromWidget::slotPressedButtonLocalLoad() in ../qt/buton_reset_settings_from_widget.cpp:47
((null):0, (null))

Warning: QObject::connect: No such slot cButtonResetSettingsFromWidget::slotPressedButtonLocalLoad() in ../qt/buton_reset_settings_from_widget.cpp:47
((null):0, (null))

Warning: QObject::connect: No such slot cButtonResetSettingsFromWidget::slotPressedButtonLocalLoad() in ../qt/buton_reset_settings_from_widget.cpp:47
((null):0, (null))

Warning: QObject::connect: No such slot cButtonResetSettingsFromWidget::slotPressedButtonLocalLoad() in ../qt/buton_reset_settings_from_widget.cpp:47
((null):0, (null))

Warning: QObject::connect: No such slot cButtonResetSettingsFromWidget::slotPressedButtonLocalLoad() in ../qt/buton_reset_settings_from_widget.cpp:47
((null):0, (null))

Warning: QObject::connect: No such slot cButtonResetSettingsFromWidget::slotPressedButtonLocalLoad() in ../qt/buton_reset_settings_from_widget.cpp:47
((null):0, (null))

**Comment by buddhi1980** [comment] 2019-02-28 21:31
Problem was caused by unfinished code.
Fixed in commit https://github.com/buddhi1980/mandelbulber2/commit/74b1f1e9b9b4dd36d126194ca43ec3c9cd4b6635

**Closed by buddhi1980** 2019-02-28 21:31 UTC
