### ISSUE TITLE
opencl anti-aliasing crash

### ISSUE THREAD

**Issue by aombk** [buddhi1980/mandelbulber2#751] opened 2019-12-15 03:37 UTC
##### System information (version)
mandelbulber-Release-x64-a229735afbd500d68d13021a0c99100ca3f7fbf2
mandelbulber-Release-x64-48fd10eaa79e4c4e8067404312c733544f16b070
Operating System / Platform => Windows 10 64 Bit

##### Detailed description

mandelbulber always crashes when i enable opencl anti-aliasing and hit render.
i get this in the command prompt:
Fatal: ASSERT failure in QVector<T>::at: "index out of range", file c:\projects\mandelbulber2\packages\bulbqt-msvc-x86.5.12.4.10787\build\native\include\qtcore\qvector.h, line 429
(c:\projects\mandelbulber2\packages\bulbqt-msvc-x86.5.12.4.10787\build\native\include\qtcore\qvector.h:429, (null))

**Comment by buddhi1980** [comment] 2019-12-15 15:44
Duplicate of #750

**Comment by buddhi1980** [comment] 2019-12-15 17:07
Fixed in commit https://github.com/buddhi1980/mandelbulber2/commit/9a966239b4912b4ce536e704d7b40cccc07f6a7b

**Closed by buddhi1980** 2019-12-15 17:07 UTC
