### ISSUE TITLE
[Bug] Mandelbulber exits when a wireless xbox360 controller disconnects

### ISSUE THREAD

**Issue by degriz** [buddhi1980/mandelbulber2#707] opened 2019-09-11 11:49 UTC
Have a standard xbox 360 controller and receiver for Windows. If Ive been using before Mandelbulber, when the controller times out and disconnects, due to no being in use, Mandelbulber exits immediately Whilst not the end of the world. Its really annoying :)

**Comment by coast77777777777** [comment] 2019-09-17 22:10
I will fix this because it also inconvenienced me.

**Comment by degriz** [comment] 2019-09-18 20:56
Thanks!

**Comment by zebastian** [comment] 2019-11-16 11:59
@degriz i will try to reproduce and fix...

**Comment by buddhi1980** [comment] 2022-02-28 19:16
Problem was fixed in this commit https://github.com/buddhi1980/mandelbulber2/commit/4ecfe2c8fa66c7f99213b9101e6921dac41608d0

**Closed by buddhi1980** 2022-02-28 19:16 UTC
Labels: BUG
